Terra Classic (LUNA) collapse for $40 billion
1712n/dn-institute pull request #110
Opened 2023-06-10 13:34 UTC by JediFaust

2023-06-10 13:36 UTC, JediFaust commented
Added detailed timeline with sources

2023-06-10 16:15 UTC, JediFaust commented
/qualitycheck

2023-06-14 14:00 UTC, evgenydmitriev requested changes

2023-06-14 14:00 UTC, evgenydmitriev commented on content/attacks/posts/2022-05-08-Terra_Classic.md
> +The crisis was the result of a combination of factors: poor decision-making by the Luna Foundation Guard (the decision to withdraw 250 million $USTC from Curve3pool), significant withdrawals by whale
Please use the bullet point structure found in other published articles.

2023-06-14 14:01 UTC, evgenydmitriev commented
Avoid any special characters apart from `-` in your file names.

2023-06-14 15:05 UTC, JediFaust commented
@evgenydmitriev fixed all issues

2023-06-14 15:27 UTC, evgenydmitriev commented
/qualitycheck

2023-06-14 22:15 UTC, jhirschkorn approved these changes

2023-06-14 22:17 UTC, jhirschkorn approved these changes

2023-06-15 14:04 UTC, evgenydmitriev approved these changes

2023-06-15 14:06 UTC, merged