Add article about Alpha Finance hack
1712n/dn-institute pull request #111
Opened 2023-06-10 22:28 UTC by sln-dns

2023-06-14 08:39 UTC, sln-dns commented
Done

2023-06-14 13:37 UTC, evgenydmitriev commented
/qualitycheck

2023-06-14 23:20 UTC, sln-dns commented
The attacker's wallet received 10,925 ETH worth roughly $20 million. 
Iron Bank received 1,000 ETH from the stolen funds. 
Alpha Homora received 1,000 ETH from the stolen funds. 
Tornado.cash received 320 ETH from the stolen funds. 

«They deposited some funds to Aave, 1,000 ETH to Iron Bank and Alpha Homora, and sent 320 ETH to Tornado.cash. That leaves just under 10,925 ETH in their wallet, worth roughly $20 million. Their funds can be viewed on [Etherscan](https://etherscan.io/address/0x905315602ed9a854e325f692ff82f58799beab57). They did it all for a transaction fee of 0.67 ETH, around $1,274.»

https://cryptobriefing.com/alpha-finance-suffers-37-5-million-loss-major-attack/

The attacker borrowed 1,000e^(18) sUSD from HomoraBankv2, utilizing UNI-WETH LP as collateral. 

"In the first stage of the attack, the attacker borrowed 1,000e18 sUSD from HomoraBankv2"

https://www.quadrigainitiative.com/casestudy/alphahomorahack.php

The attacker borrowed 1,000e^(18) sUSD from HomoraBankv2, utilizing UNI-WETH LP as collateral. 
The attacker exploited a rounding error in the protocol during repayment, resulting in a debt of 19709787742197 and a total borrow share of 1. 
The attacker took advantage of a rounding error in the protocol during repayment. 

«In the first stage of the attack, the attacker borrowed 1,000e18 sUSD from HomoraBankv2 using UNI-WETH LP (previously received from Uniswap pool in [this transaction](https://etherscan.io/tx/0x4441eefe434fbef9d9b3acb169e35eb7b3958763b74c5617b39034decd4dd3ad)) as collateral.
When the debt was paid back in a later transaction, the attacker owed 1000.000098548938710984 sUSD (due to interest) but only paid 1000.000098548938710983 sUSD, exploiting a rounding error in the protocol. After this occurs, the attacker called resolveReserve on the sUSD bank to create a debt of 19709787742197 and leaving the total borrow share at 1.»
https://www.halborn.com/blog/post/explained-the-alpha-homora-defi-hack-feb-2021

The USDC, USDT, and DAI were subsequently deposited into Aave to acquire aTokens, which were then added to Curve's a3Crv pool. 

«This hoard of cySUSD enabled the attacker to borrow the following (as shown above):
13.2k WETH
3.6M USDC
5.6M USDT
4.2M DAI
Of these the USDC, USDT, and DAI were all deposited to Aave as shown above to get aTokens.  These tokens were then deposited to Curve’s a3Crv pool, which are added to Curve’s liquidity gauge.»


https://www.halborn.com/blog/post/explained-the-alpha-homora-defi-hack-feb-2021



The team collaborated with authorities and cybersecurity experts to trace the stolen funds and prevent the attacker from profiting. 

«Dear Alpha community, we've been notified of an exploit on Alpha Homora V2. We're now working with @AndreCronjeTech and @CreamdotFinance  together on this.
The loophole has been patched.»

https://twitter.com/stellaxyz_/status/1360535699368251394?s=20

"We are investigating with the relevant parties and will investigate with the authorities to trace the attacker." "No user funds were lost, and Alpha and CREAM teams are working on how to heal the debt between the protocols. The loophole that made the exploit possible has been closed, and the project is going through peer review and another security audit ––Alpha Homora V2 had been audited by Quantstamp and Peckshield."

https://www.quadrigainitiative.com/casestudy/alphahomorahack.php

2023-06-15 15:29 UTC, eric-oconnor requested changes
Please add the links you provided in the comments to the post, where the bot identified an error. This will help the bot and team in the fact checking process.

2023-06-15 16:35 UTC, sln-dns commented
> `Alpha Finance was hacked on February 13, 2021, exploiting a vulnerability in the Alpha Homora v2 contract.` white_check_mark Multiple sources confirm that Alpha Finance was hacked on February 13, 2021, exploiting a vulnerability in the Alpha Homora v2 contract. The attacker was able to extract $37.5 million from the project.

> `The attacker successfully extracted $37.5 million from the project.` white_check_mark Multiple sources confirm that Alpha Homora was hacked and the attacker successfully extracted $37.5 million from the project using a flash loan-based price manipulation tactic.
 
> `The identity of the attackers involved in the Alpha Finance DeFi hack remains unknown.` white_check_mark None of the search results provide any information about the identity of the attackers involved in the Alpha Finance DeFi hack. Therefore, the claim is true.
 
> `Information using in this incident was not publicly available and was not accessible through the user interface, suggesting that the attacker may have possessed insider knowledge to carry out the attack.` white_check_mark The search results show that Alpha Finance was hacked in February 2021, with the attacker exploiting a vulnerability in the Alpha Homora v2 contract to extract $37.5 million from the project. The information used in the attack was not publicly available and not accessible through the user interface, indicating that the attacker may have had insider knowledge to carry out the attack. This supports the claim that the attacker may have possessed insider knowledge.
 
> `The Alpha Finance DeFi hack resulted in financial losses of $37.5 million.` white_check_mark Multiple sources confirm that Alpha Finance was hacked in February 2021 and $37.5 million was stolen from the project.
 
> `The stolen funds were distributed among various destinations, including Aave, Iron Bank, Alpha Homora, Tornado.cash, and the attacker's wallet.` white_check_mark The search results confirm that Alpha Homora and Cream Finance were exploited in a flash loan attack, resulting in the theft of $37.5 million. The attack was carried out using Alpha Homora through the borrowing of sUSD from IronBank. Therefore, the claim that the stolen funds were distributed among various destinations, including Aave, Iron Bank, Alpha Homora, Tornado.cash, and the attacker's wallet is true.
 
> `The attacker's wallet received 10,925 ETH worth roughly $20 million.` x There is no evidence in the search results to support this claim. The largest amount stolen from a DeFi project mentioned in the search results is $37.5 million, and it is not clear whether the entire amount was transferred to the attacker's wallet or distributed across multiple wallets.

https://cryptobriefing.com/alpha-finance-suffers-37-5-million-loss-major-attack/

> `Iron Bank received 1,000 ETH from the stolen funds.` x There is no evidence in the search results to support or refute the claim that Iron Bank received 1,000 ETH from the stolen funds. The search results only mention that Cream Finance's Iron Bank protocol was involved in the exploit that led to the theft of $37.5 million from Alpha Finance, but there is no information on how much of the stolen funds went to Iron Bank or any other specific party.

https://cryptobriefing.com/alpha-finance-suffers-37-5-million-loss-major-attack/

> `Alpha Homora received 1,000 ETH from the stolen funds.` x There is no evidence in the search results that Alpha Homora received 1,000 ETH from the stolen funds. The search results only mention that Alpha Homora was hacked and lost $37.5 million in February 2021.

https://cryptobriefing.com/alpha-finance-suffers-37-5-million-loss-major-attack/

> `Tornado.cash received 320 ETH from the stolen funds.` x There is no mention of Tornado.cash receiving 320 ETH in the search results. The articles only mention Cream Finance and Alpha Finance being exploited in DeFi attacks, resulting in millions of dollars being stolen. One article mentions that 100 ETH was sent to Tornado Cash from the stolen funds, but this is not enough evidence to verify the claim that Tornado.cash received 320 ETH.

https://cryptobriefing.com/alpha-finance-suffers-37-5-million-loss-major-attack/

> `The specific amount of stolen funds received by Aave is not provided.` white_check_mark None of the search results mention Aave being involved in any hack or exploit, so there is no evidence to suggest that any funds were stolen from Aave.
 
> `Alpha Homora V2 was hacked on February 13, 2021.` white_check_mark Multiple sources confirm that Alpha Homora V2 was hacked on February 13, 2021, resulting in a loss of $37.5 million.
 
> `The attacker borrowed 1,000e^(18) sUSD from HomoraBankv2, utilizing UNI-WETH LP as collateral.` x There is no evidence in the search results to support or refute this claim. The search results only mention that Alpha Homora was exploited by an attacker who drained over $37 million, but do not provide details on the specific methods used by the attacker.

https://www.quadrigainitiative.com/casestudy/alphahomorahack.php
https://www.halborn.com/blog/post/explained-the-alpha-homora-defi-hack-feb-2021

> `The attacker exploited a rounding error in the protocol during repayment, resulting in a debt of 19709787742197 and a total borrow share of 1.` x There is no evidence in the search results to support or refute this claim. The search results only provide information about exploits and attacks on DeFi protocols, but do not mention a specific rounding error resulting in the stated debt and borrow share.

https://www.halborn.com/blog/post/explained-the-alpha-homora-defi-hack-feb-2021

> `The attacker amassed a substantial hoard of cySUSD, which is a collateralized version of sUSD, by engaging in multiple transactions involving borrowing and lending sUSD between Alpha Homora and Iron Bank.` white_check_mark Multiple sources confirm that Alpha Homora was exploited and drained of over $37 million by an attacker who leveraged Cream's Iron Bank protocol-to-protocol lending. The attacker took advantage of a vulnerability in Alpha Homora's v2 contract and used a multi-step process involving a series of flash loans to carry out the attack. While the specific details of the attacker's transactions involving borrowing and lending sUSD are not mentioned in the search results, it is reasonable to conclude that the attacker amassed a substantial hoard of cySUSD as claimed.
 
> `The attacker obtained loans of various assets, including 13.2k WETH, 3.6M USDC, 5.6M USDT, and 4.2M DAI.` white_check_mark Multiple sources confirm that Alpha Finance was exploited in a flash loan attack, resulting in the attacker obtaining over $37 million. The specific assets obtained by the attacker are not mentioned in the search results, but it is reasonable to assume that they include the assets listed in the claim.
 
> `The USDC, USDT, and DAI were subsequently deposited into Aave to acquire aTokens, which were then added to Curve's a3Crv pool.` x There is no evidence in the search results to support or refute this claim. The search results only provide information about DeFi hacks and attacks on Cream Finance and Alpha Finance, but do not mention anything about Aave or Curve's a3Crv pool.

https://www.halborn.com/blog/post/explained-the-alpha-homora-defi-hack-feb-2021

> `The extracted Ether was distributed among different destinations, including Iron Bank, Alpha Homora, Tornado.cash, and the attacker's wallet.` white_check_mark The claim is true. According to the search results, Alpha Homora was exploited in a hack that resulted in the attacker extracting $37.5 million. Cream's Iron Bank protocol-to-protocol lending was leveraged in the attack. The attacker took over $37.5 million through a multi-step process involving a series of flash loans. Additionally, the search results do not mention Tornado.cash, but they do not disprove the claim either.
 
> `In response to the hack, the Alpha Finance team rectified the rounding er [...]

2023-06-20 19:20 UTC, eric-oconnor commented
> > `Alpha Finance was hacked on February 13, 2021, exploiting a vulnerability in the Alpha Homora v2 contract.` white_check_mark Multiple sources confirm that Alpha Finance was hacked on February 13, 2021, exploiting a vulnerability in the Alpha Homora v2 contract. The attacker was able to extract $37.5 million from the project.
> 
> > `The attacker successfully extracted $37.5 million from the project.` white_check_mark Multiple sources confirm that Alpha Homora was hacked and the attacker successfully extracted $37.5 million from the project using a flash loan-based price manipulation tactic.
> 
> > `The identity of the attackers involved in the Alpha Finance DeFi hack remains unknown.` white_check_mark None of the search results provide any information about the identity of the attackers involved in the Alpha Finance DeFi hack. Therefore, the claim is true.
> 
> > `Information using in this incident was not publicly available and was not accessible through the user interface, suggesting that the attacker may have possessed insider knowledge to carry out the attack.` white_check_mark The search results show that Alpha Finance was hacked in February 2021, with the attacker exploiting a vulnerability in the Alpha Homora v2 contract to extract $37.5 million from the project. The information used in the attack was not publicly available and not accessible through the user interface, indicating that the attacker may have had insider knowledge to carry out the attack. This supports the claim that the attacker may have possessed insider knowledge.
> 
> > `The Alpha Finance DeFi hack resulted in financial losses of $37.5 million.` white_check_mark Multiple sources confirm that Alpha Finance was hacked in February 2021 and $37.5 million was stolen from the project.
> 
> > `The stolen funds were distributed among various destinations, including Aave, Iron Bank, Alpha Homora, Tornado.cash, and the attacker's wallet.` white_check_mark The search results confirm that Alpha Homora and Cream Finance were exploited in a flash loan attack, resulting in the theft of $37.5 million. The attack was carried out using Alpha Homora through the borrowing of sUSD from IronBank. Therefore, the claim that the stolen funds were distributed among various destinations, including Aave, Iron Bank, Alpha Homora, Tornado.cash, and the attacker's wallet is true.
> 
> > `The attacker's wallet received 10,925 ETH worth roughly $20 million.` x There is no evidence in the search results to support this claim. The largest amount stolen from a DeFi project mentioned in the search results is $37.5 million, and it is not clear whether the entire amount was transferred to the attacker's wallet or distributed across multiple wallets.
> 
> https://cryptobriefing.com/alpha-finance-suffers-37-5-million-loss-major-attack/
> 
> > `Iron Bank received 1,000 ETH from the stolen funds.` x There is no evidence in the search results to support or refute the claim that Iron Bank received 1,000 ETH from the stolen funds. The search results only mention that Cream Finance's Iron Bank protocol was involved in the exploit that led to the theft of $37.5 million from Alpha Finance, but there is no information on how much of the stolen funds went to Iron Bank or any other specific party.
> 
> https://cryptobriefing.com/alpha-finance-suffers-37-5-million-loss-major-attack/
> 
> > `Alpha Homora received 1,000 ETH from the stolen funds.` x There is no evidence in the search results that Alpha Homora received 1,000 ETH from the stolen funds. The search results only mention that Alpha Homora was hacked and lost $37.5 million in February 2021.
> 
> https://cryptobriefing.com/alpha-finance-suffers-37-5-million-loss-major-attack/
> 
> > `Tornado.cash received 320 ETH from the stolen funds.` x There is no mention of Tornado.cash receiving 320 ETH in the search results. The articles only mention Cream Finance and Alpha Finance being exploited in DeFi attacks, resulting in millions of dollars being stolen. One article mentions that 100 ETH was sent to Tornado Cash from the stolen funds, but this is not enough evidence to verify the claim that Tornado.cash received 320 ETH.
> 
> https://cryptobriefing.com/alpha-finance-suffers-37-5-million-loss-major-attack/
> 
> > `The specific amount of stolen funds received by Aave is not provided.` white_check_mark None of the search results mention Aave being involved in any hack or exploit, so there is no evidence to suggest that any funds were stolen from Aave.
> 
> > `Alpha Homora V2 was hacked on February 13, 2021.` white_check_mark Multiple sources confirm that Alpha Homora V2 was hacked on February 13, 2021, resulting in a loss of $37.5 million.
> 
> > `The attacker borrowed 1,000e^(18) sUSD from HomoraBankv2, utilizing UNI-WETH LP as collateral.` x There is no evidence in the search results to support or refute this claim. The search results only mention that Alpha Homora was exploited by an attacker who drained over $37 million, but do not provide details on the specific methods used by the attacker.
> 
> https://www.quadrigainitiative.com/casestudy/alphahomorahack.php https://www.halborn.com/blog/post/explained-the-alpha-homora-defi-hack-feb-2021
> 
> > `The attacker exploited a rounding error in the protocol during repayment, resulting in a debt of 19709787742197 and a total borrow share of 1.` x There is no evidence in the search results to support or refute this claim. The search results only provide information about exploits and attacks on DeFi protocols, but do not mention a specific rounding error resulting in the stated debt and borrow share.
> 
> https://www.halborn.com/blog/post/explained-the-alpha-homora-defi-hack-feb-2021
> 
> > `The attacker amassed a substantial hoard of cySUSD, which is a collateralized version of sUSD, by engaging in multiple transactions involving borrowing and lending sUSD between Alpha Homora and Iron Bank.` white_check_mark Multiple sources confirm that Alpha Homora was exploited and drained of over $37 million by an attacker who leveraged Cream's Iron Bank protocol-to-protocol lending. The attacker took advantage of a vulnerability in Alpha Homora's v2 contract and used a multi-step process involving a series of flash loans to carry out the attack. While the specific details of the attacker's transactions involving borrowing and lending sUSD are not mentioned in the search results, it is reasonable to conclude that the attacker amassed a substantial hoard of cySUSD as claimed.
> 
> > `The attacker obtained loans of various assets, including 13.2k WETH, 3.6M USDC, 5.6M USDT, and 4.2M DAI.` white_check_mark Multiple sources confirm that Alpha Finance was exploited in a flash loan attack, resulting in the attacker obtaining over $37 million. The specific assets obtained by the attacker are not mentioned in the search results, but it is reasonable to assume that they include the assets listed in the claim.
> 
> > `The USDC, USDT, and DAI were subsequently deposited into Aave to acquire aTokens, which were then added to Curve's a3Crv pool.` x There is no evidence in the search results to support or refute this claim. The search results only provide information about DeFi hacks and attacks on Cream Finance and Alpha Finance, but do not mention anything about Aave or Curve's a3Crv pool.
> 
> https://www.halborn.com/blog/post/explained-the-alpha-homora-defi-hack-feb-2021
> 
> > `The extracted Ether was distributed among different destinations, including Iron Bank, Alpha Homora, Tornado.cash, and the attacker's wallet.` white_check_mark The claim is true. According to the search results, Alpha Homora was exploited in a hack that resulted in the attacker extracting $37.5 million. Cream's Iron Bank protocol-to-protocol lending was leveraged in the attack. The attacker took over $37.5 million through a multi-step process involving a series of flash loans. Additionally, the search results do not mention Tornado.cash, but they do not disprove the cla [...]

2023-06-24 22:20 UTC, sln-dns commented
> status?
If I understood your comment about adding links correctly, I did it above by adding all the links to the bot-marked paragraphs. If possible, please review.

2023-06-26 01:50 UTC, jhirschkorn commented
> > status?
> > If I understood your comment about adding links correctly, I did it above by adding all the links to the bot-marked paragraphs. If possible, please review.

add relevant links to appropriate sections in the article

2023-06-28 16:14 UTC, eric-oconnor approved these changes
links added to the correct section

2023-06-29 10:50 UTC, JediFaust requested changes
After addressing the changes, please, resolve conflicts with the [main](https://github.com/1712n/dn-institute/tree/main) branch

2023-06-29 10:50 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +categories: DeFi, Protocol Exploit
Reformat categories like in Verge incident:
>attacks/posts/categories:
    - 51%
    - Protocol exploit

2023-06-29 10:50 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +The identity of the attackers involved in the Alpha Finance DeFi hack remains unknown. Information using in this incident was not publicly available and was not accessible through the user interface,
Shorten first sentence, and remove the second one. Add attacker address instead.

2023-06-29 10:50 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> + ## [Losses](https://cryptobriefing.com/alpha-finance-suffers-37-5-million-loss-major-attack/)
Don't put source links in section itself. It can be moved to the first sentence in the section

2023-06-29 10:50 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +The Alpha Finance DeFi hack resulted in financial losses, with $37.5 million extracted from the project. The stolen funds were distributed among various destinations as follows:
Shorten the first sentence

2023-06-29 10:50 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +  + Aave: the specific amount is not provided.
Remove the line, or specify the amount

2023-06-29 10:50 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +
Shorten the whole section, leaving only important events. All the description should be summarized and move to the Summary section

2023-06-29 10:50 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +- **Insufficient Validation and Access Controls:** The lack of strict validation checks and access controls for custom spells and critical functions allowed unauthorized manipulation of the protocol.
What 'custom spells' mean? I assume there is no such terminology in blockchain or smart contracts. Rephrase please

2023-06-29 10:50 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +
Remove unnecessary lines, leave only one

2023-07-03 19:08 UTC, JediFaust requested changes
I appreciate your effort to write an article. Please, rewrite it, using other approved posts as a reference, and most reliable sources

2023-07-03 19:08 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +- **Post-Hack:**
Rewrite with accurate time

2023-07-03 19:08 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +In the initial stage, the attacker borrowed [1,000e^(18)](https://www.quadrigainitiative.com/casestudy/alphahomorahack.php) sUSD from HomoraBankv2, utilizing [UNI-WETH LP](https://www.halborn.com/blo
Please, leave only one or two short sentences in timeline, and move important details to the Summary section, as said in previous comments

2023-07-03 19:08 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +    - 51%
It's not a 51% attack
> At the end of the day, the Alpha Homora attacker was able to make approximately $37.5 million by exploiting the vulnerable contract.

I recommend to investigate the case, trying to understand it before writing an article. 
So category is DeFi and Flash loan attack

2023-07-04 15:06 UTC, JediFaust requested changes

2023-07-04 15:06 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +On February 13, 2021, Alpha Finance, a DeFi project, suffered a hack that resulted in a $37.5 million loss. The attacker exploited a rounding error in the repayment process, accumulating a substantia
Rewrite last sentence, unnecessary repetition

2023-07-04 15:06 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +In the initial stage, the [attacker](https://etherscan.io/tx/0x2b419173c1f116e94e43afed15a46e3b3a109e118aba166fcca0ba583f686d23) borrowed [1,000e^(18)](https://www.quadrigainitiative.com/casestudy/al
In your article link is on 'attacker' word lead to a transaction. Fix please.

2023-07-04 15:06 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +- **Post-Hack:**
Rewrite 'Post-Hack' with accurate time

2023-07-05 21:44 UTC, JediFaust requested changes

2023-07-05 21:44 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
>  An [agreement](https://etherscan.io/address/0x141e0541d87c6cbdbf2a6a8104248b4b922f629e?ref=blog.alphaventuredao.io#code) is reached between Alpha Homora V2 (Alpha Finance Lab) and CREAM V2 (CREAM) re
Clean source link

2023-07-05 21:44 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +In the initial stage, the [attacker](https://etherscan.io/address/0x905315602ed9a854e325f692ff82f58799beab57) borrowed [1,000e^(18)](https://www.quadrigainitiative.com/casestudy/alphahomorahack.php)
Remove 'In the initial stage'

2023-07-09 06:19 UTC, JediFaust commented
Status?

2023-07-09 19:21 UTC, JediFaust requested changes

2023-07-09 19:21 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
>  An [agreement](https://etherscan.io/address/0x141e0541d87c6cbdbf2a6a8104248b4b922f629e?ref=blog.alphaventuredao.io#code) is reached between Alpha Homora V2 (Alpha Finance Lab) and CREAM V2 (CREAM) re
Please, shorten the etherscan link by deleting `?ref=...` in the end of the link

2023-07-09 19:21 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +categories:
Rewrite headers according to [new changes](https://github.com/1712n/dn-institute#readme). In this case, `entity-types` are `DeFi` and `Yield Aggregator`, and `attack -types` are `Smart Contract Exploit` and `Flash Loan Attack`

2023-07-10 08:54 UTC, JediFaust requested changes

2023-07-10 08:54 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +- Alpha Finance
Rewrite target entities as:
 - Alpha Homora
 - Iron Bank

2023-07-13 17:05 UTC, JediFaust requested changes
Fix title pls, there is typo

2023-07-14 10:18 UTC, JediFaust requested changes

2023-07-14 10:18 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Alpha-Finance.md
> +title: "Alpha Finance DeFi Smart Contract Exploit Attack: $37.5 Million Exploited"
Please, rewrite as `Alpha Finance suffered a Flash Loan Attack: $37.5 Million Exploited`

2023-07-17 18:46 UTC, JediFaust approved these changes

2023-07-25 21:46 UTC, evgenydmitriev approved these changes

2023-07-25 21:46 UTC, merged

2023-07-25 21:46 UTC, evgenydmitriev commented
/payout

2023-07-25 21:51 UTC, evgenydmitriev commented
@danisztls https://github.com/1712n/dn-institute/actions/runs/5662119579/job/15341431180#step:5:91

2023-07-27 03:42 UTC, evgenydmitriev commented
/payout