An article about the Nomad hack in August 2022.
1712n/dn-institute pull request #123
Opened 2023-06-21 04:13 UTC by L0nest

2023-06-22 15:27 UTC, evgenydmitriev requested changes
Harmony Horizon's hack [already exists](https://github.com/1712n/dn-institute/blob/main/content/attacks/posts/2022-06-23-Harmony-Horizon.md). Remove it from your pr.

2023-06-28 03:32 UTC, L0nest commented
> Harmony Horizon's hack [already exists](https://github.com/1712n/dn-institute/blob/main/content/attacks/posts/2022-06-23-Harmony-Horizon.md). Remove it from your pr.

2023-06-28 23:27 UTC, JediFaust requested changes

2023-06-28 23:27 UTC, JediFaust commented on content/attacks/posts/2022-08-01-Nomad.md
> +**Smart Contract Vulnerability:** The security failure in the Nomad bridge occurred due to a mistake made during the contract update process. This highlights the need for comprehensive code review an
Remove last two sentences and add more details about the vulnerability itself

2023-06-28 23:27 UTC, JediFaust commented on content/attacks/posts/2022-08-01-Nomad.md
> +- **August 1, 2022 11:25 PM GMT:** [The project team reported](https://twitter.com/nomadxyz_/status/1554246853348036608) that they know about the hack.
Rephrase the sentence, fix grammar issue

2023-06-28 23:27 UTC, JediFaust commented on content/attacks/posts/2022-08-01-Nomad.md
> +- **August 2, 2022 10:26 PM GMT:** [The project team stated](https://twitter.com/nomadxyz_/status/1554413278406721537?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1554413278406721537%7Ctwgr%5
Fix source link by removing unnecessary characters from URL

2023-06-28 23:27 UTC, JediFaust commented on content/attacks/posts/2022-08-01-Nomad.md
> +After a frenzied hack from hundreds of wallets, the bridge’s TVL dropped from $190,740,000 to $1,794 in mere hours.
Add a total loss

2023-06-29 07:48 UTC, L0nest commented on content/attacks/posts/2022-08-01-Nomad.md
> +**Smart Contract Vulnerability:** The security failure in the Nomad bridge occurred due to a mistake made during the contract update process. This highlights the need for comprehensive code review an
Corrected

2023-06-29 10:02 UTC, JediFaust requested changes
Resolve conflicts with the [main](https://github.com/1712n/dn-institute/tree/main) branch please

2023-06-29 10:52 UTC, JediFaust requested changes
Please, resolve conflicts with the [main](https://github.com/1712n/dn-institute/tree/main) branch

2023-06-29 11:08 UTC, L0nest commented
> Please, resolve conflicts with the [main](https://github.com/1712n/dn-institute/tree/main) branch

Check, please

2023-06-30 04:51 UTC, JediFaust approved these changes

2023-06-30 04:53 UTC, JediFaust commented
/qualitycheck

2023-06-30 05:09 UTC, JediFaust commented
@evgenydmitriev Can be merged after approval

2023-06-30 08:47 UTC, evgenydmitriev commented
![image](https://github.com/1712n/dn-institute/assets/56804873/3dab0d71-d3a7-4ba0-9d75-0b67e45d42a8)

2023-07-05 03:11 UTC, L0nest commented
> ![image](https://user-images.githubusercontent.com/56804873/250042313-3dab0d71-d3a7-4ba0-9d75-0b67e45d42a8.png)

I'm sorry, I did not come across this check, do I need to make any changes?

2023-07-05 21:49 UTC, JediFaust requested changes
Yeah, try to rewrite some parts with your own words

2023-07-09 06:17 UTC, JediFaust requested changes

2023-07-09 06:17 UTC, JediFaust commented on content/attacks/posts/2022-08-01-Nomad.md
> +categories: Bridge Hack
Please, reformat headers regarding with [new changes](https://github.com/1712n/dn-institute/tree/main#readme). Here is an example:
```
target-entities: Nomad
entity-types:
- DeFi
- Exchange
attack-types:
- Smart Contract Exploit
```

2023-07-09 19:35 UTC, JediFaust requested changes
I assume misunderstanding happened here, sorry for that. I just pointed before headers as an example, and Nomad is not an Exchange. I wrote previous headers as an example. Here is right headers for Nomad case:
entity-types:
    - DeFi
    - Bridge
attack-types:
    - Smart Contract Exploit
    - Signarute Verification Issue

2023-07-10 08:57 UTC, JediFaust requested changes
Please, merge [1712n:main](https://github.com/1712n/dn-institute/tree/main) into your branch

2023-07-13 16:53 UTC, L0nest commented
> Please, merge [1712n:main](https://github.com/1712n/dn-institute/tree/main) into your branch

Merged

2023-07-13 17:08 UTC, JediFaust approved these changes
Thanks!

2023-07-13 17:09 UTC, JediFaust commented
@evgenydmitriev can be merged after approval, all changes addressed

2023-07-13 17:26 UTC, evgenydmitriev approved these changes

2023-07-13 17:27 UTC, merged