add post 51% BitcoinCash
1712n/dn-institute pull request #125
Opened 2023-06-21 15:28 UTC by kishoian

2023-06-22 15:58 UTC, jhirschkorn requested changes

2023-06-22 15:58 UTC, jhirschkorn commented on content/attacks/posts/2018-11-AurumCoin-Cryptopia
> +title: AurumCoin Users Face Losses in a 51% Attack
add quotations to the title

2023-06-22 15:58 UTC, jhirschkorn commented on content/attacks/posts/2018-11-AurumCoin-Cryptopia
> +The attackers behind the 51% attack on AurumCoin remain unidentified. They were able to accumulate a majority of the network’s hash power, thereby taking control of the AurumCoin blockchain. This con
dont simply restate info from the summary. add info about the attackers or just leave the comment that they are unknown.

2023-06-22 15:58 UTC, jhirschkorn commented on content/attacks/posts/2018-11-AurumCoin-Cryptopia
> +- **Following Days:** The cryptocurrency community discusses the implications of the attack, with many raising concerns regarding the security of smaller cryptocurrencies like AurumCoin.
delete the "following days" line. it's unnecessary.

2023-06-22 16:03 UTC, jhirschkorn requested changes

2023-06-22 16:23 UTC, jhirschkorn commented
/qualitycheck

2023-06-22 18:30 UTC, jhirschkorn approved these changes

2023-06-22 18:33 UTC, jhirschkorn commented
can you add links to sources to address the following issues from the bot:

> AurumCoin network experienced a sudden increase in hash rate in November 2018. ❌
> The claim is false. The search results indicate that AurumCoin was hit by a 51% attack in November 2018, resulting in a loss of funds for the Cryptopia exchange. A 51% attack means that a hacker takes control over a crypto network with more than 51% of its hash rate. This means that the hash rate of the network did not increase suddenly, but rather was taken over by the attacker. Therefore, the claim is false.

2023-06-23 05:04 UTC, kishoian commented
I already deleted this part about increasing hash rate

2023-06-23 13:53 UTC, merged

2023-06-23 13:53 UTC, jhirschkorn commented
/payout