Update 2021-08-10-poly-network.md
1712n/dn-institute pull request #130
Opened 2023-06-22 10:11 UTC by kishoian

2023-06-22 18:44 UTC, jhirschkorn requested changes

2023-06-22 18:44 UTC, jhirschkorn commented on content/attacks/posts/2021-08-10-poly-network.md
> +title: Poly Network Hack - $610 Million Stolen in 2021
Add quotes to title

2023-06-22 18:44 UTC, jhirschkorn commented on content/attacks/posts/2021-08-10-poly-network.md
> +- **Lack of security updates:** Poly Network had not released a sec
?

2023-06-23 13:49 UTC, jhirschkorn commented
/qualitycheck

2023-06-26 01:53 UTC, jhirschkorn approved these changes

2023-06-26 01:54 UTC, merged

2023-06-26 01:54 UTC, jhirschkorn commented
/payout

2023-06-26 05:59 UTC, albina-at-inca commented
@kishoian please send me your preferred payment method along with the wallet address to wiki.challenge.bounties@dn.institute