2022-09-20-Wintermute
1712n/dn-institute pull request #136
Opened 2023-06-22 17:26 UTC by JediFaust

2023-06-22 19:41 UTC, jhirschkorn commented
/qualitycheck

2023-06-22 19:47 UTC, jhirschkorn commented
please add a citation/reference for the following bot comment(s):

> The attack was executed through a brute force private key compromise. ❌
> There is no evidence in the search results to suggest that the attack on Wintermute was executed through a brute force private key compromise. The articles only mention that the company was hacked and lost $160 million worth of cryptocurrency.

2023-06-22 21:54 UTC, jhirschkorn requested changes

2023-06-22 21:54 UTC, jhirschkorn commented on content/attacks/posts/2022-09-20-Wintermute.md
> +On September 20, 2022, Wintermute, a London-based algorithmic market maker offering liquidity across Centralized Finance (CeFi) and Decentralized Finance (DeFi) exchanges and over-the-counter (OTC) d
add a reference for brute force key compromise

2023-06-22 21:54 UTC, jhirschkorn commented on content/attacks/posts/2022-09-20-Wintermute.md
> +The identity of the attackers remains unknown. The Ethereum address linked to the attacker and currently holding all stolen funds:
add current as of date to address holding funds

2023-06-22 21:54 UTC, jhirschkorn commented on content/attacks/posts/2022-09-20-Wintermute.md
> +**Profanity's Vulnerability:** An inherent weakness in Profanity's code allowed the attacker to generate all potential keys for a vanity address by bruteforcing the private keys, scan associated acco
add citation if possible

2023-06-23 12:24 UTC, JediFaust commented on content/attacks/posts/2022-09-20-Wintermute.md
> +**Profanity's Vulnerability:** An inherent weakness in Profanity's code allowed the attacker to generate all potential keys for a vanity address by bruteforcing the private keys, scan associated acco
Done

2023-06-23 12:24 UTC, JediFaust commented on content/attacks/posts/2022-09-20-Wintermute.md
> +The identity of the attackers remains unknown. The Ethereum address linked to the attacker and currently holding all stolen funds:
Done

2023-06-23 12:25 UTC, JediFaust commented on content/attacks/posts/2022-09-20-Wintermute.md
> +On September 20, 2022, Wintermute, a London-based algorithmic market maker offering liquidity across Centralized Finance (CeFi) and Decentralized Finance (DeFi) exchanges and over-the-counter (OTC) d
Done

2023-06-23 14:52 UTC, jhirschkorn approved these changes

2023-06-23 14:53 UTC, merged

2023-06-23 14:53 UTC, jhirschkorn commented
/payout