Deribit
1712n/dn-institute pull request #146
Opened 2023-06-27 12:15 UTC by kishoian

2023-06-27 15:00 UTC, eric-oconnor requested changes

2023-06-27 15:00 UTC, eric-oconnor commented on content/attacks/posts/2022-11-01-Deribit.md
> +categories: Custodian
Add quotes around the Categories: "Type of Attack"

2023-06-27 15:16 UTC, eric-oconnor reviewed
/qualitycheck

2023-06-27 15:48 UTC, evgenydmitriev commented
/qualitycheck

2023-06-29 05:11 UTC, jhirschkorn commented
Double check dates and reconcile with bot comments

2023-06-29 10:08 UTC, JediFaust commented on content/attacks/posts/2022-11-01-Deribit.md
> +- **November 2, 2022:** Deribit says it will cover the losses from the hack using its own funds.
Provide source please

2023-06-29 14:37 UTC, eric-oconnor approved these changes
quotes added

2023-06-30 04:39 UTC, merged

2023-06-30 04:54 UTC, JediFaust commented
/payout

2023-06-30 08:44 UTC, evgenydmitriev commented
/payout