Ascend ex
1712n/dn-institute pull request #147
Opened 2023-06-27 14:36 UTC by kishoian

2023-06-27 15:00 UTC, eric-oconnor requested changes

2023-06-27 15:15 UTC, eric-oconnor reviewed
/qualitycheck

2023-06-29 05:24 UTC, jhirschkorn commented
/quality check

2023-06-29 10:11 UTC, JediFaust requested changes

2023-06-29 10:11 UTC, JediFaust commented on content/attacks/posts/2021-12-11-AscendEX.md
> +The identity of the attacker or attackers who conducted the hot wallet breach on the AscendEX network remains unknown.
Shorten the sentence

2023-06-29 10:11 UTC, JediFaust commented on content/attacks/posts/2021-12-11-AscendEX.md
> +The attackers managed to steal approximately [$77 million worth](https://twitter.com/peckshield/status/1469915194004766722) of assets from the AscendEX network. This included USDT, BNB, MATIC, and ot
Remove last sentence

2023-06-29 10:11 UTC, JediFaust commented on content/attacks/posts/2021-12-11-AscendEX.md
> +- **December 11, 2021:** The hot wallet breach on the AscendEX network begins. The attackers gain access to the wallet and withdraw a total of $77 million worth of assets.
Delete first sentence

2023-06-29 10:11 UTC, JediFaust commented on content/attacks/posts/2021-12-11-AscendEX.md
> +- **December 13, 2021:** The AscendEX team reimburses all affected users and announces that they are working with law enforcement to track down the attacker.
Provide source

2023-06-29 10:11 UTC, JediFaust commented on content/attacks/posts/2021-12-11-AscendEX.md
> +The AscendEX team has not released any specific details about the security failures that led to the hack.
Make a bullet point, and add one most possible reason

2023-06-29 14:43 UTC, eric-oconnor approved these changes
Quotes added to category

2023-07-03 19:22 UTC, JediFaust commented
<img width="539" alt="image" src="https://github.com/1712n/dn-institute/assets/83595409/d838d46a-82d2-4e68-ab50-122fca7c2d15">

2023-07-04 15:30 UTC, JediFaust requested changes
Please, merge main into the branch

2023-07-05 21:51 UTC, JediFaust approved these changes

2023-07-05 21:56 UTC, JediFaust requested changes
Please resolve conflicts

2023-07-05 22:17 UTC, merged

2023-07-05 22:30 UTC, JediFaust commented
/payout