2021-06023-Haven-Protocol
1712n/dn-institute pull request #149
Opened 2023-06-27 18:30 UTC by lz-tmz

added article in wiki

2023-06-27 19:14 UTC, JediFaust requested changes

2023-06-27 19:14 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +   - Open up the repository to more developers and ensure git history is included. See [GitHub](https://github.com/).
The text is unrelated to the incident, please, rewrite the whole article. Take a look into approved articles, to find out what is wrong with the structure too.

2023-06-29 05:28 UTC, jhirschkorn requested changes
Fix timeline bullet format

2023-06-29 05:30 UTC, jhirschkorn requested changes

2023-06-29 05:30 UTC, jhirschkorn commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +-**June 22, 2021  18:19:41:**
If including the actual time is necessary, also include the relevant time zone for clarity.

2023-06-29 05:30 UTC, jhirschkorn commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +## Timeline
Clean up the timeline. Too verbose. Make it shorter.

2023-07-03 19:54 UTC, JediFaust requested changes

2023-07-03 19:54 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +## Losses
Add total lost amount

2023-07-03 19:54 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +Haven Protocol experienced a series of exploits that resulted in financial losses and raised concerns about the security of the platform. The exploits targeted various aspects of the protocol, includ
Add more technical details with reliable sources

2023-07-03 19:54 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +The identity of the attackers remains unknown.
Add attacker's address

2023-07-03 19:54 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +- **July 19, 2021:** Chain rollback through a [fork](https://havenprotocol.medium.com/haven-protocol-successfully-deploys-rollback-hard-fork-206e5ead190e), allowing exchange wallets to reopen and on-
Shorten timeline, providing important events and sources. Look up on other approved articles as a reference

2023-07-03 19:54 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +## Security Failure Causes
Add sources and make bullet point as in other approved articles

2023-07-05 22:12 UTC, JediFaust requested changes

2023-07-05 22:12 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +Haven Protocol experienced a series of exploits that resulted in financial losses. The attacker [manipulated](https://havenprotocol.org/wp-content/uploads/2021/07/Technical-Overview-of-June-2021-Expl
There is no such thing as 'manipulating transaction'. Also, source is not accessible by now.

2023-07-05 22:12 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +The identity of the attackers remains unknown. The attacker address involved in the Haven Protocol exploit is not publicly disclosed or known.
Remove the last sentence, was thinking the address is known.

2023-07-05 22:12 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
>  - TradeOgre froze 100,000 XHV, valued at approximately $350,000.
Reformat as `$4,335,000 worth 125.66 xBTC` for all further lines

2023-07-05 22:12 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +- **June 24, 2021:** An exploit in the xAsset conversion validation.
Rewrite the line with your own words

2023-07-05 22:12 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +- **June 29, 2021:** an exploit was leveraged that allowed for minting of 9m xUSD.
Rewrite with your own words

2023-07-05 22:12 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
>  - **July 19, 2021:** Chain rollback through a [fork](https://havenprotocol.medium.com/haven-protocol-successfully-deploys-rollback-hard-fork-206e5ead190e), allowing exchange wallets to reopen and on-
Rewrite like 'Haven Protocol performed a rollback'

2023-07-05 22:12 UTC, JediFaust commented on content/attacks/posts/2021-06-23-Haven-Protocol.md
> +- Insufficient attention to development practices.
Format bullet points and return explanations. Just look up on approved articles in the main branch.

2023-07-17 18:48 UTC, JediFaust commented
No update for 2 weeks. Closing.

2023-07-17 18:48 UTC, closed without merging