Create 2022-04-30-Fei-Protocol.md
1712n/dn-institute pull request #154
Opened 2023-06-28 14:52 UTC by kishoian

2023-06-28 15:04 UTC, kishoian commented
Can I ask?

It seems to me that the categories are not quite right. Bridge Hack and Flash loan attacks are always DeFI and Protocol Exploit

If we use categories like 51% and Custodian it would be better to add only DeFi here. 
Bridge Hack, Flash loan, Phishing, etc - additional different tags

2023-06-29 10:22 UTC, JediFaust requested changes

2023-06-29 10:22 UTC, JediFaust commented on content/attacks/posts/2022-04-30-Fei-Protocol.md
> +- **April 30, 2022, 09:34 AM +UTC:** [Smart contract analysis firm Block Sec tweets about it](https://twitter.com/BlockSecTeam/status/1520350965274386433)
Unnecessary point

2023-06-29 10:22 UTC, JediFaust commented on content/attacks/posts/2022-04-30-Fei-Protocol.md
> +- **Reentrancy vulnerabilities occur in a smart contract:** The attacker [exploited two functions within the contracts of Fei Protocol](https://www.halborn.com/blog/post/explained-the-fei-protocol-ha
Leave the title of the cause as Reentrancy Vulnerability

2023-06-29 10:24 UTC, JediFaust commented
> Can I ask?
> 
> It seems to me that the categories are not quite right. Bridge Hack and Flash loan attacks are always DeFI and Protocol Exploit
> 
> If we use categories like 51% and Custodian it would be better to add only DeFi here. Bridge Hack, Flash loan, Phishing, etc - additional different tags

Good point, we are working on it. If you have any regarding ideas, feel free to share, would appreciate it.

2023-07-09 06:49 UTC, JediFaust requested changes

2023-07-09 06:49 UTC, JediFaust commented on content/attacks/posts/2022-04-30-Fei-Protocol.md
> +- Smart Contract Exploit
Add Reentrancy Attack as an attack type

2023-07-09 06:49 UTC, JediFaust commented on content/attacks/posts/2022-04-30-Fei-Protocol.md
> +- Fei Protocol
Add `Rari Capital` as an entity

2023-07-09 06:49 UTC, JediFaust commented on content/attacks/posts/2022-04-30-Fei-Protocol.md
> +- DeFi
Add `Lending Platform` as an entity type

2023-07-09 06:53 UTC, JediFaust requested changes
Please, address requested changes and merge main

2023-07-09 06:53 UTC, JediFaust commented on content/attacks/posts/2022-04-30-Fei-Protocol.md
> +- **April 30, 2022, 09:34 AM +UTC:** [Smart contract analysis firm Block Sec tweets about it](https://twitter.com/BlockSecTeam/status/1520350965274386433)
Status?

2023-07-10 08:44 UTC, JediFaust requested changes
Please, add `Lending Platform` as an entity type and `Rari Capital` as a target entity. Also, Shorten the security failure cause as `Reentrancy Vulnerability`

2023-07-11 21:18 UTC, JediFaust approved these changes

2023-07-11 21:18 UTC, merged

2023-07-11 21:18 UTC, JediFaust commented
/payout