Create 2021-02-13-Cream-Finance.md
1712n/dn-institute pull request #155
Opened 2023-06-29 09:34 UTC by kishoian

2023-06-29 09:34 UTC, kishoian commented
Help me to understand, please. What events in the timeline are considered significant? Is what I wrote enough or do I need more details? I can specify each translation in the smart contract, but then it will be too much, but if you do not write about translations, then there are too few events. Every hack is the same: the attack started, the company announced the hack, and the attack ended

2023-06-29 14:23 UTC, kishoian commented
Does the Bitstamp article have a good timeline? I think not. But if so, then I can write such with links to statements

2023-06-30 05:42 UTC, JediFaust requested changes
It's unclear which protocol suffered from the hack, and how CREAM and Alpha Homora related to each other. Please, extend an article.

2023-06-30 05:42 UTC, JediFaust commented on content/attacks/posts/2021-02-13-Cream-Finance.md
> +- ~13,244 WETH
Add worth of WETH at the moment of an incident, It can be calculated easily.

2023-07-02 15:08 UTC, kishoian commented
I see that you've changed the categories on the website once again. You asked for feedback, so here are my thoughts:

I believe that categories should be distinctly segregated and should not overlap, as it can lead to confusion. We could classify all the articles based on the type of attacks; I have sketched out a rough idea below.

Main Categories:

- Protocol Exploits
Description: Articles about hacks that occur due to vulnerabilities in the protocols themselves.

- Interaction Attacks
Description: Articles about attacks based on manipulating interactions between smart contracts or protocols, including reentrancy, flash loans, etc.

- Key and Access Thefts
Description: Articles about cases of private key theft, phishing, and other methods of unauthorized access.

- Data Manipulation
Description: Articles about oracle attacks, price manipulations, and other ways of data tampering.

As for the current elements that are designated as categories, these could be integrated as tags. Often, a hack simultaneously falls under multiple descriptors such as bridge hack, DeFi, and protocol vulnerability. Labeling these as categories might be unconventional, but employing them as tags would be more appropriate.

Only tags without categories be better also

2023-07-03 20:10 UTC, JediFaust commented
> I see that you've changed the categories on the website once again. You asked for feedback, so here are my thoughts:
> 
> I believe that categories should be distinctly segregated and should not overlap, as it can lead to confusion. We could classify all the articles based on the type of attacks; I have sketched out a rough idea below.
> 
> Main Categories:
> 
>     * Protocol Exploits
>       Description: Articles about hacks that occur due to vulnerabilities in the protocols themselves.
> 
>     * Interaction Attacks
>       Description: Articles about attacks based on manipulating interactions between smart contracts or protocols, including reentrancy, flash loans, etc.
> 
>     * Key and Access Thefts
>       Description: Articles about cases of private key theft, phishing, and other methods of unauthorized access.
> 
>     * Data Manipulation
>       Description: Articles about oracle attacks, price manipulations, and other ways of data tampering.
> 
> 
> As for the current elements that are designated as categories, these could be integrated as tags. Often, a hack simultaneously falls under multiple descriptors such as bridge hack, DeFi, and protocol vulnerability. Labeling these as categories might be unconventional, but employing them as tags would be more appropriate.
> 
> Only tags without categories be better also

Appreciate sharing thoughts! Although, I think more accurate sepparation 

> I see that you've changed the categories on the website once again. You asked for feedback, so here are my thoughts:
> 
> I believe that categories should be distinctly segregated and should not overlap, as it can lead to confusion. We could classify all the articles based on the type of attacks; I have sketched out a rough idea below.
> 
> Main Categories:
> 
>     * Protocol Exploits
>       Description: Articles about hacks that occur due to vulnerabilities in the protocols themselves.
> 
>     * Interaction Attacks
>       Description: Articles about attacks based on manipulating interactions between smart contracts or protocols, including reentrancy, flash loans, etc.
> 
>     * Key and Access Thefts
>       Description: Articles about cases of private key theft, phishing, and other methods of unauthorized access.
> 
>     * Data Manipulation
>       Description: Articles about oracle attacks, price manipulations, and other ways of data tampering.
> 
> 
> As for the current elements that are designated as categories, these could be integrated as tags. Often, a hack simultaneously falls under multiple descriptors such as bridge hack, DeFi, and protocol vulnerability. Labeling these as categories might be unconventional, but employing them as tags would be more appropriate.
> 
> Only tags without categories be better also

Thanks for sharing thoughts! I think this categories does not include 51% attack and front-run attacks for example. And the main categories should include wide range of attacks as well. I think, this list is pretty solid, but need to be reworked and extended.

2023-07-03 20:13 UTC, JediFaust commented
Article is on pause, since there is another, earlier article is on pending state

2023-07-04 02:54 UTC, kishoian commented
oh, I didn't notice it. *crying

2023-07-04 15:12 UTC, JediFaust commented
No worries) It took time to figure it out, since articles was named differently

2023-07-27 19:35 UTC, JediFaust commented
The same incident was already merged, closing

2023-07-27 19:35 UTC, closed without merging