2022-10-11-Mango-Markets.md
1712n/dn-institute pull request #160
Opened 2023-07-01 18:16 UTC by jwalin12

2023-07-01 19:30 UTC, evgenydmitriev commented
/qualitycheck

2023-07-01 19:46 UTC, jwalin12 commented
Wallet 1 placed a MNGO-SOL Perp Sell Order for 483 million MNGO perpetual futures at 3.8 cents per future ❌ , 
Wallet 2 bought the MNGO-SOL Sell Order from Wallet 1, effectively opening a MNGO long position for Wallet 2. ❌ and
Hacker's Wallet 1 and Wallet 2 were funded with 5 million USDC each. ❌ can be verified by the markdown links already attached

2023-07-01 19:57 UTC, jwalin12 commented
/qualitycheck

2023-07-03 20:18 UTC, JediFaust requested changes

2023-07-03 20:18 UTC, JediFaust commented on content/attacks/posts/2022-10-11-Mango-Markets.md
> +About USD $116 Million worth of crypto assets in terms of USDC, stablecoins and SOL was borrowed and never returned to the platform.
Funds were recovered by the exploiter, add a source

2023-07-09 13:46 UTC, jwalin12 commented on content/attacks/posts/2022-10-11-Mango-Markets.md
> +About USD $116 Million worth of crypto assets in terms of USDC, stablecoins and SOL was borrowed and never returned to the platform.
Updated

2023-07-09 19:29 UTC, JediFaust requested changes
Please, make sure you are checking the article using [language tool service](https://languagetool.org/) and fix grammar and punctuation issues. Spelling issues are okay, since it detects token symbols as a mistake but the are not. Also, read [new changes to headers](https://github.com/1712n/dn-institute#readme) and apply them.

2023-07-11 22:05 UTC, JediFaust requested changes
Please, merge [main](https://github.com/1712n/dn-institute/tree/main) into the branch

2023-07-11 22:05 UTC, JediFaust commented on content/attacks/posts/2022-10-11-Mango-Markets.md
> +entity-types: Protocol
Rewrite as follows, and discover [new changes](https://github.com/1712n/dn-institute/tree/main#readme) with list of common examples
```code
entity-types:
  - DeFi
  - Exchange

2023-07-11 22:05 UTC, JediFaust commented on content/attacks/posts/2022-10-11-Mango-Markets.md
> +attack-types: Protocol Vulnerability, Oracle Exploit
Rewrite as:
```code
attack-types:
  - Price Oracle Manipulation

2023-07-13 19:02 UTC, JediFaust requested changes

2023-07-17 17:02 UTC, JediFaust requested changes

2023-07-17 17:02 UTC, JediFaust commented on content/attacks/posts/2022-10-11-Mango-Markets.md
> +On October 11th, 2022, Mango Markets, a decentralized exchange on Solana, was exploited. The hacker manipulated the price oracle for the protocol's MNGO token. The hacker first took out a long MNGO p
Please, rewrite the summary, with less `the hacker` word. Rephrase or combine sentences, and use synonyms as `attacker` etc.

2023-07-22 00:28 UTC, JediFaust approved these changes
Thanks! Make sure to check grammar issues in further contributions)

2023-07-22 00:28 UTC, merged

2023-07-22 00:28 UTC, JediFaust commented
/payout

2023-07-27 15:37 UTC, albina-at-inca commented
@jwalin12 can you please email your BTC address to [albina.bashaeva@inca.digital](mailto:albina.bashaeva@inca.digital)?

Please include the QR code.