Create 2023-05-01-Level-Finance.md
1712n/dn-institute pull request #161
Opened 2023-07-02 16:54 UTC by kishoian

2023-07-03 20:24 UTC, JediFaust requested changes

2023-07-03 20:24 UTC, JediFaust commented on content/attacks/posts/2023-05-01-Level-Finance.md
> +brc-20:
Delete the line, or rewrite. ERC20 and BEP20 is a token standards, BSC is a chain.

2023-07-03 20:24 UTC, JediFaust commented on content/attacks/posts/2023-05-01-Level-Finance.md
> +- **May 1, 2023, 05:50:41 PM +UTC:** [First succesfull hack attempt](https://bscscan.com/tx/0xe1f257041872c075cbe6a1212827bc346df3def6d01a07914e4006ec43027165)
Please, make sure to perform grammar checks.

2023-07-04 02:48 UTC, kishoian commented on content/attacks/posts/2023-05-01-Level-Finance.md
> +brc-20:
of course, it was an accidental typo

2023-07-04 15:10 UTC, JediFaust requested changes

2023-07-04 15:10 UTC, JediFaust commented on content/attacks/posts/2023-05-01-Level-Finance.md
> +bsc-20:
Leave as 'BSC' please. [FYI](https://www.google.com/search?q=what+is+bsc+and+bep20+difference)

2023-07-06 00:02 UTC, JediFaust requested changes
Please, update regarding with recent changes of headers format which can be found in [readme](https://github.com/1712n/dn-institute/tree/main#readme) and update with main branch

2023-07-06 22:45 UTC, JediFaust requested changes

2023-07-06 22:45 UTC, JediFaust commented on content/attacks/posts/2023-05-01-Level-Finance.md
> +type of entity: "Blockchain"
Rewrite as 
>target-entities: Silk Road 
entity-types: 
    - Darknet
    - Market
attack-types: 
    - Web Infrastructure Attack
    - Race Condition Exploit

2023-07-06 22:45 UTC, JediFaust commented on content/attacks/posts/2023-05-01-Level-Finance.md
> +type of entity: "Blockchain"
Type of Entities for Level Finance are: DeFi, Exchange

2023-07-06 22:45 UTC, JediFaust commented on content/attacks/posts/2023-05-01-Level-Finance.md
> +type of attack: "Protocol exploit"
Type of attack is 'Smart Contract Exploit'

2023-07-09 06:57 UTC, JediFaust requested changes

2023-07-09 06:57 UTC, JediFaust commented on content/attacks/posts/2023-05-01-Level-Finance.md
> +- **Protocol exploit:** The Level Finance hack was made possible by failed precondition checks. In theory, the protocol is designed to allow a user to claim a referral reward once per epoch. However,
Security Failure Cause cannot be `Protocol Exploit` change as `Failed Precondition Checks`

2023-07-09 08:30 UTC, JediFaust approved these changes

2023-07-09 08:30 UTC, merged

2023-07-09 08:33 UTC, JediFaust commented
/payout