Create 2023-02-02-BonqDAO-AllianceBlock.md
1712n/dn-institute pull request #185
Opened 2023-07-13 13:22 UTC by kishoian

2023-07-13 13:36 UTC, evgenydmitriev requested changes

2023-07-13 13:36 UTC, evgenydmitriev commented on content/attacks/posts/2023-02-02-BonqDAO-AllianceBlock.md
> +## Security Failure Causes
When you write about security failure causes, please generalize them to something that is a common problem in IT Security. Listing facts that contributed to the possibility of the attack isn't helpful for the modeling we do based on the wiki articles. This applies to your other submissions as well.

2023-07-13 13:36 UTC, evgenydmitriev commented on content/attacks/posts/2023-02-02-BonqDAO-AllianceBlock.md
> +- **Single Source of Truth for Price Data:** Relying on a single source for price data left BonqDAO vulnerable to this kind of attack. Had the protocol used multiple price sources, the attacker's man
"Single Source of Truth" has a [positive connotation in system design](https://en.wikipedia.org/wiki/Single_source_of_truth). The more appropriate section title would be something like "Lack of oracle information sources diversity and resilience".

2023-07-13 13:36 UTC, evgenydmitriev commented on content/attacks/posts/2023-02-02-BonqDAO-AllianceBlock.md
> +- **February 1, 2023:** - The attacker deflates the $WALBT token value and liquidates other users' collateral.
Merge identical timestamps into one line and rewrite it as one paragraph.

2023-07-19 21:10 UTC, JediFaust requested changes

2023-07-19 21:10 UTC, JediFaust commented on content/attacks/posts/2023-02-02-BonqDAO-AllianceBlock.md
> +- AllianceBlock
Remove the line, it was not hacked directly

2023-07-19 21:10 UTC, JediFaust commented on content/attacks/posts/2023-02-02-BonqDAO-AllianceBlock.md
> +In February 2023, BonqDAO, a lending and stablecoin platform hosted on the Polygon network, faced a substantial security breach. A malicious actor exploited a flaw in a smart contract associated with
Phrase `stablecoin platform` is not suitable here, remove the line please. Leave as a lending platform.

2023-07-19 21:10 UTC, JediFaust commented on content/attacks/posts/2023-02-02-BonqDAO-AllianceBlock.md
> +- Token
Remove the line

2023-07-19 21:10 UTC, JediFaust commented on content/attacks/posts/2023-02-02-BonqDAO-AllianceBlock.md
> +The hack resulted in approximately $120 million in losses for the BonqDAO.
Simplify and shorten

2023-07-19 21:10 UTC, JediFaust commented on content/attacks/posts/2023-02-02-BonqDAO-AllianceBlock.md
> +- **Lack of Oracle Information Sources Diversity and Resilience:** Relying on a single source for price data left BonqDAO vulnerable to this kind of attack. Had the protocol used multiple price sourc
`Lack of Oracle Diversity` will be better

2023-08-02 03:39 UTC, evgenydmitriev commented
@kishoian, you need to mark the conversations as resolved and ping the reviewers in the comment section if you want them to check your pull request again. Otherwise, it will be considered as work in progress.

2023-08-04 14:50 UTC, JediFaust requested changes

2023-08-17 14:12 UTC, jhirschkorn commented
@kishoian status?

2023-08-17 21:07 UTC, JediFaust approved these changes

2023-08-17 23:23 UTC, evgenydmitriev approved these changes

2023-08-17 23:24 UTC, merged

2023-08-17 23:24 UTC, evgenydmitriev commented
/payout