Create 23-07-30-CurveFi
1712n/dn-institute pull request #223
Opened 2023-08-24 17:47 UTC by Adelaar5

2023-08-24 18:15 UTC, jhirschkorn commented
/qualitycheck

2023-08-24 18:59 UTC, jhirschkorn requested changes

2023-08-24 18:59 UTC, jhirschkorn commented on content/attacks/posts/23-07-30-CurveFi
> +Curve ranks among the most esteemed and reliable DEXes and relies on automated market makers in much the same way as Uniswap. Though it is still functioning, Curve has seen an exodus of funds since t
Remove the second half of the last sentence. not necessary

2023-08-24 18:59 UTC, jhirschkorn commented on content/attacks/posts/23-07-30-CurveFi
> +As illustrated below, the enigmatic exploiter has been returning some of the funds.
remove "enigmatic"

2023-08-24 18:59 UTC, jhirschkorn commented on content/attacks/posts/23-07-30-CurveFi
> +Just under $16 million of the hacked funds are still sitting in 0xb1c33b391c2569b737ec387e731e88589e8ec148 as of 08.22.
full date in DD MMM YYYY format

2023-08-24 18:59 UTC, jhirschkorn commented on content/attacks/posts/23-07-30-CurveFi
> +The hacker did, however, return around $12.7 million to Alchemix, accompanied with a cryptic [message](https://etherscan.io/idm?tx=0x23c4799784c91023204bd68a94ec7a963486f2485dc43c13d8b804d5301b8041)
dont speculate about the message. remove the last sentence.

2023-08-25 15:16 UTC, Adelaar5 commented
Hi Jules, I've added all of your suggestions. Regarding the quality check, seems like it's flagging statements involving info that it just can't find, even links and wallet addresses that are listed. Do you want responses to each red x? 

Upon review, I'd say the facts are tight, barring a few unknown wallets floating around and some flexibility on the dollar amounts (depending on who's doing the conversions; really tough for example to give msETH a valuation, given it's never had much volume to speak of).

2023-08-25 15:27 UTC, jhirschkorn commented
> Hi Jules, I've added all of your suggestions. Regarding the quality check, seems like it's flagging statements involving info that it just can't find, even links and wallet addresses that are listed. Do you want responses to each red x?
> 
> Upon review, I'd say the facts are tight, barring a few unknown wallets floating around and some flexibility on the dollar amounts (depending on who's doing the conversions; really tough for example to give msETH a valuation, given it's never had much volume to speak of).

the bot is pretty dumb so dont spend too much time fighting it. just give the flagged statements a quick check.  Ignore it if it doesnt check out or add an additional citation if it might make things clearer. you already have a number of good citations in the article tho.  i will review again later today and merge. thanks for your submission.

2023-08-25 18:07 UTC, jhirschkorn requested changes

2023-08-25 18:07 UTC, jhirschkorn commented on content/attacks/posts/23-07-30-CurveFi
> +Just under $16 million of the hacked funds are still sitting in 0xb1c33b391c2569b737ec387e731e88589e8ec148 as of 25 08 2023.
date format should read 25 AUG 2023

2023-08-25 18:07 UTC, jhirschkorn commented
one more small fix

2023-08-25 18:22 UTC, Adelaar5 commented on content/attacks/posts/23-07-30-CurveFi
> +Just under $16 million of the hacked funds are still sitting in 0xb1c33b391c2569b737ec387e731e88589e8ec148 as of 25 08 2023.
Ah, misunderstood that. Have changed; all caps for the month right?

2023-08-25 19:29 UTC, jhirschkorn approved these changes

2023-08-25 19:30 UTC, merged

2023-08-25 19:30 UTC, jhirschkorn commented
/payout

2023-08-26 09:05 UTC, albina-at-inca commented
> ## How to Claim Bounty
> Email your bitcoin/lightning payment address to [wiki.challenge.bounties@dn.institute](mailto:wiki.challenge.bounties@dn.institute). Expect all payouts to be completed by the end of the month.

@Adelaar5 can you send me your BTC address? Please include the QR code.

2023-08-28 13:55 UTC, Adelaar5 commented
@albina-at-inca Just emailed. Please let me know if there are any issues!

2023-08-28 14:21 UTC, albina-at-inca commented
> @albina-at-inca Just emailed. Please let me know if there are any issues!

Received, thank you.