2019-03-25-CoinBene
1712n/dn-institute pull request #232
Opened 2023-08-30 21:34 UTC by JediFaust

2023-08-30 21:34 UTC, JediFaust commented
/qualitycheck

2023-09-01 20:06 UTC, evgenydmitriev commented
/qualitycheck

2023-09-07 21:12 UTC, jhirschkorn requested changes

2023-09-07 21:12 UTC, jhirschkorn commented on content/attacks/posts/2019-03-25-CoinBene.md
> +CoinBene lost $105,150,329 worth of various assets. The most valuable [stolen assets breakdown](https://github.com/elementus-io/coinbene-analysis#market-value-of-assets-withdrawn):
The second sentence here is a little awkward.  Suggest: "Breakdown of top 5 stolen assets by value:"

2023-09-07 21:12 UTC, jhirschkorn commented on content/attacks/posts/2019-03-25-CoinBene.md
> +- **March 20, 2019:** [Bitwise's presentation to the SEC](https://www.sec.gov/comments/sr-nysearca-2019-01/srnysearca201901-5164833-183434.pdf) mentioned CoinBene, with the suspicions of wash trading
...mentioned suspicions of wash trading on CoinBene

2023-09-07 21:12 UTC, jhirschkorn commented on content/attacks/posts/2019-03-25-CoinBene.md
> +- **April 9, 2019:** PeckShield, a blockchain security company, [published a report](https://peckshield.medium.com/coinbene-incident-investigation-report-6d4a3ed3b715) stating that the stolen funds w
...funds were transferred to centralized exchanges,...

2023-09-08 05:53 UTC, JediFaust commented
/qualitycheck

2023-09-12 19:44 UTC, jhirschkorn commented
@JediFaust are you still workkng this one?

2023-09-12 19:46 UTC, JediFaust commented
> @JediFaust are you still workkng this one?

Yeah, but no need to merge yet, will debug grammar checker on this one

2023-09-13 18:12 UTC, jhirschkorn approved these changes

2023-09-13 18:12 UTC, merged

2023-09-13 18:13 UTC, jhirschkorn commented
/payout -x 2