Lazarus Involved Stake.com Article
1712n/dn-institute pull request #257
Opened 2023-09-16 12:38 UTC by JediFaust

Stake.com incident Lazarus Group involved

2023-09-16 12:38 UTC, JediFaust commented
/qualitycheck

2023-09-16 13:07 UTC, JediFaust commented
/qualitycheck

2023-09-18 19:51 UTC, jhirschkorn requested changes

2023-09-18 19:51 UTC, jhirschkorn commented on content/attacks/posts/2023-09-04-Stake.md
> +On September 4, 2023, Stake.com, a crypto gambling protocol offering casino games and sports betting, was targeted by the Lazarus Group (also known as APT38), a group of DPRK cyber actors. The group
Last sentence:
Some affected addresses held over $13 million worth of various tokens as of...

2023-09-18 19:51 UTC, jhirschkorn commented on content/attacks/posts/2023-09-04-Stake.md
> +The FBI has identified the Lazarus Group as the responsible party for this attack. The following addresses were used to transfer the funds:
Can you add a link to the FBI source for this?

2023-09-18 23:10 UTC, JediFaust commented on content/attacks/posts/2023-09-04-Stake.md
> +On September 4, 2023, Stake.com, a crypto gambling protocol offering casino games and sports betting, was targeted by the Lazarus Group (also known as APT38), a group of DPRK cyber actors. The group
Done

2023-09-19 17:06 UTC, jhirschkorn approved these changes

2023-09-19 17:07 UTC, merged

2023-09-19 17:08 UTC, jhirschkorn commented
/payout -x 3