2017-04-22-Yapizon
1712n/dn-institute pull request #265
Opened 2023-09-22 08:09 UTC by LiquidVac

2023-09-22 20:31 UTC, jhirschkorn commented
/qualitycheck

2023-09-22 20:46 UTC, jhirschkorn commented
fix grammar issues #5, 7, 9, 10, 11

2023-09-22 20:53 UTC, jhirschkorn requested changes

2023-09-22 20:53 UTC, jhirschkorn commented on content/attacks/posts/2017-04-22-Yapizon.md
> +The total losses are 3816 BTC, equivalent to around $5.5 million [(about 37% of Yapizon total assets)](https://mrhacker.co/news/south-korean-bitcoin-exchange-yapizon-hacked-5-million-stolen)].
extra ]?

2023-09-22 20:53 UTC, jhirschkorn commented on content/attacks/posts/2017-04-22-Yapizon.md
> +The total losses are 3816 BTC, equivalent to around $5.5 million [(about 37% of Yapizon total assets)](https://mrhacker.co/news/south-korean-bitcoin-exchange-yapizon-hacked-5-million-stolen)].
add in the date related to the conversion of btc to $.  ie "equivalent to around $5.5m as of _date"_

2023-09-22 20:53 UTC, jhirschkorn commented on content/attacks/posts/2017-04-22-Yapizon.md
> +- **April 26, 2017:** Yapizon [has suspended operations for the next few days](https://www.cryptoninjas.net/2017/04/26/south-korean-bitcoin-exchange-yapizon-hacked-3831-btc/) in order to finish accou
change to Yapizon [suspends operations for the next few days]...

2023-09-22 20:53 UTC, jhirschkorn commented on content/attacks/posts/2017-04-22-Yapizon.md
> +Yapizon has not officially announced what exactly allowed the hackers to access its system. Several possible reasons:
dont speculate. if there are credible sources that discuss reasons for the hack, you can mention/link them.  otherwise just leave as unknown.

2023-09-22 20:53 UTC, jhirschkorn commented on content/attacks/posts/2017-04-22-Yapizon.md
> +On April 22, 2017, Yapizon, a South Korean cryptocurrency exchange,[suffered a security breach](https://www.newsbtc.com/news/south-korean-yapizon-bitcoin-exchange-confirms-hack-loses-5-mil-bitcoin/)
remove "Later" from the last sentence. --> After this incident the exchange...

2023-09-22 20:53 UTC, jhirschkorn commented on content/attacks/posts/2017-04-22-Yapizon.md
> +[Lazarus Group](https://cointelegraph.com/news/south-korean-bitcoin-exchange-yapizon-starts-trading-bitcoin-cash), a North Korean hacker crew has been accused of carrying out the heist. That was one
change "crew" to "group"

2023-09-22 20:53 UTC, jhirschkorn commented on content/attacks/posts/2017-04-22-Yapizon.md
> +[Lazarus Group](https://cointelegraph.com/news/south-korean-bitcoin-exchange-yapizon-starts-trading-bitcoin-cash), a North Korean hacker crew has been accused of carrying out the heist. That was one
Last sentence, change "That" to "This"

2023-09-23 14:39 UTC, JediFaust commented
@LiquidVac The case is already covered: [Coinbin-Youbit-Yapizon](https://dn.institute/attacks/posts/2019-02-20-Coinbin/)

2023-09-23 17:28 UTC, closed without merging