Created a wiki post for a mixin network hack at 2023-09-23
1712n/dn-institute pull request #270
Opened 2023-09-27 17:56 UTC by snakerzr

Hello. My name is Alexander Evdokimov. I have created a wiki post for a mixin network hack at 2023-09-23 as a condition for applying for an Investigation analyst. https://geekjob.ru/vacancy/65129c9538bb26b34f002489

2023-09-28 08:50 UTC, JediFaust commented
/qualitycheck

2023-09-28 08:59 UTC, JediFaust requested changes

2023-09-28 08:59 UTC, JediFaust commented on content/attacks/posts/2023-09-23-Mixin-Network.md
> +- **September 25, 2023, 02:40 AM UTC:** Mixin Network [confirmed](https://twitter.com/MixinKernel/status/1706139175018529139) the attack, suspended services, anounced a public mandarin livestream at
Remove the line, avoid duplicate sources please

2023-09-28 08:59 UTC, JediFaust commented on content/attacks/posts/2023-09-23-Mixin-Network.md
> +- **September 25,2023, 06:48 AM UTC:** [PeckShieldAlert](https://twitter.com/peckshieldalert/status/1706199059705598406?s=52&t=yv7fZgVN8INf98Rdhx6jXQ) reported on amount of funds stolen.
Remove unnecessary line

2023-09-28 08:59 UTC, JediFaust commented on content/attacks/posts/2023-09-23-Mixin-Network.md
> +- **September 25, 2023, 09:28 AM UTC:** [Lookonchain](https://twitter.com/lookonchain/status/1706239132585148907) reported on amount of funds stolen too.
Remove unnecessary line

2023-09-28 08:59 UTC, JediFaust commented on content/attacks/posts/2023-09-23-Mixin-Network.md
> +- **September 25, 2023, 2:48 PM UTC:** BlockSec, crypto security firm, [shares it's findings](https://twitter.com/BlockSecTeam/status/1706319766544155068):
Remove unnecessary line, single source that reported an issue is enough

2023-09-28 08:59 UTC, JediFaust commented on content/attacks/posts/2023-09-23-Mixin-Network.md
> +- **September 27, 2023, 08:27 AM UTC:** Mixin Network made a [statement](https://twitter.com/MixinKernel/status/1706948541850235274), that they are working with Google (Mandiant) and SlowMist Team, b
Remove last sentence

2023-09-28 08:59 UTC, JediFaust commented on content/attacks/posts/2023-09-23-Mixin-Network.md
> +Mixin Network lost $141,328,868.21 [identified](https://twitter.com/peckshieldalert/status/1706199059705598406?s=52&t=yv7fZgVN8INf98Rdhx6jXQ) from reportedly around $200M in total across the followin
Clean the source link and remove `... in total across the following chains:`

2023-09-28 08:59 UTC, JediFaust commented on content/attacks/posts/2023-09-23-Mixin-Network.md
> +North Korean Lazarus Group is [suspected](https://rekt.news/mixin-rekt/#:~:text=This%20case%20has%20many%20of%20the%20hallmarks%20of%20a%20Lazarus%20heist%2C%20who%20have%20been%20plenty%20busy%20lat
Clean the source link for rekt.news and remove bleeping computer source

2023-09-28 15:30 UTC, snakerzr commented
@JediFaust  Made a new commit, resolved issues. Should I verify the claims that the bot did not confirm?

2023-10-02 18:52 UTC, JediFaust commented
> @JediFaust Made a new commit, resolved issues. Should I verify the claims that the bot did not confirm?

No need

2023-10-02 18:52 UTC, JediFaust approved these changes
Good job!

2023-10-02 18:53 UTC, merged

2023-10-02 18:57 UTC, JediFaust commented
/payout -x 2

2023-10-11 09:15 UTC, snakerzr commented
@christina-tkach I believe you are hiring for the investigation analyst vacancy, and this PR is part of my application for the position. It seems like I can't get in touch with you. Could you please clarify whether there will be a next step for me? I have another offer that I need to respond to by this Friday. The details are in the email I sent you earlier to hygge.team@. Thank you.

2023-10-11 10:39 UTC, christina-tkach commented
>@christina-tkach I believe you are hiring for the investigation analyst vacancy, and this PR is part of my application for the position. It seems like I can't get in touch with you. Could you please clarify whether there will be a next step for me? I have another offer that I need to respond to by this Friday. The details are in the email I sent you earlier to hygge.team@. Thank you.

@snakerzr thanks for reaching out here, I contacted you via email