2023-01-12-Lendhub.md
1712n/dn-institute pull request #278
Opened 2023-10-12 12:21 UTC by svg-arch

2023-10-12 17:03 UTC, JediFaust requested changes

2023-10-12 17:03 UTC, JediFaust commented on content/attacks/posts/2023-01-12-Lendhub.md
> +- **January 12, 2023:**  Lendhub is hacked
Provide malicious transaction with exact time if possible, the sentence looks incomplete.

2023-10-12 17:03 UTC, JediFaust commented on content/attacks/posts/2023-01-12-Lendhub.md
> +The main reason for the Lendhub attack was the failure to remove a deprecated token from the market properly. This vulnerability allowed attackers to exploit the protocol's smart contracts and steal
Make bullet point as in other articles, provide little more details and shorten or remove last sentence

2023-10-14 17:56 UTC, JediFaust requested changes

2023-10-14 17:56 UTC, JediFaust commented on content/attacks/posts/2023-01-12-Lendhub.md
> +- **Old and new IBSV tokens exist simultaneously:** This made it possible to mint and redeem tokens on the old market, while simultaneously borrowing money against them on the new market
The bullet point should be common cause, I would suggest `Dev Team Negligence`. And mention that main reason was overlooked deprecated token from the market, in the description itself.

2023-10-16 13:20 UTC, JediFaust approved these changes

2023-10-16 13:20 UTC, JediFaust commented
/payout

2023-10-16 13:21 UTC, merged

2023-10-16 13:36 UTC, albina-at-inca commented
@svg-arch please email your BTC address to wiki.challenge.bounties@dn.institute including QR code.