Add article about Coincheck Hack
1712n/dn-institute pull request #28
Opened 2023-05-23 17:37 UTC by sln-dns

2023-05-30 15:51 UTC, eric-oconnor reviewed
Regarding the 1st Submission: Poly Network Exploited, Largest DeFi Hack in Histor, there should be a y at the end of History

Regarding the 2nd Submission: Could you please add the relevant details regarding the hacker groups that are associated to this event and if there have been any additional updates.

Overall the submissions are decent, some quality assurance checks and clarifying details around these events should result in a successful submission.

2023-05-31 16:18 UTC, sln-dns commented
> 


I could not find a source that made a definite judgment about the involvement of any group in this attack. 

The source would have to include an unambiguous identification of the attack, namely the date, the platform, the coins stolen, and the approximate amount. 

If you have any information or remember some facts but don't remember where you saw it, please let me know and I will make an effort to find information to update the article.

2023-05-31 16:35 UTC, eric-oconnor commented
> > 
> 
> I could not find a source that made a definite judgment about the involvement of any group in this attack.
> 
> The source would have to include an unambiguous identification of the attack, namely the date, the platform, the coins stolen, and the approximate amount.
> 
> If you have any information or remember some facts but don't remember where you saw it, please let me know and I will make an effort to find information to update the article.

Correct in noting the lack of a definitive attribution, this is an important distinction to make while annotating data.  

While the attributions to a particular group are not definitive, they contain indispensable data and correlating attributes which are indispensable to be aware of when studying these attacks like vectors and methods, i.e., types of viruses or SE methods.  

Omitting information due to weak correlation keeps us from learning what is and isn't essential to be aware of in the future.

2023-05-31 18:23 UTC, sln-dns commented
> 

Please check the new version of my article. I have changed the paragraph "Attackers"

[2019-01-28-Coincheck Hack.md](https://github.com/1712n/dni-website/files/11617689/2019-01-28-Coincheck.Hack.md)

2023-05-31 23:10 UTC, evgenydmitriev commented
> > 
> 
> Please check the new version of my article. I have changed the paragraph "Attackers"
> 
> [2019-01-28-Coincheck Hack.md](https://github.com/1712n/dni-website/files/11617689/2019-01-28-Coincheck.Hack.md)

@sln-dns all your edits should be visible [here](https://github.com/1712n/dni-website/pull/28/files)

2023-05-31 23:39 UTC, sln-dns commented
Now I believe everything should be correct

2023-05-31 23:43 UTC, evgenydmitriev requested changes
I reviewed only one article, but the same applies to the other one

2023-05-31 23:43 UTC, evgenydmitriev commented on content/attacks/posts/2010-08-10-poly-network.md
> +## Lessons Learned
don't invent sections. follow the structure outlined in the majority of the articles

2023-05-31 23:43 UTC, evgenydmitriev commented on content/attacks/posts/2010-08-10-poly-network.md
> +The attack exploited a critical vulnerability in the Poly Network's smart contracts, enabling the unauthorized transfer of assets between different blockchain networks. The incident shed light on the
provide technical details, avoid general phrases about the importance of something

2023-05-31 23:43 UTC, evgenydmitriev commented on content/attacks/posts/2010-08-10-poly-network.md
> +The attack led to the theft of approximately $600 million worth of various cryptocurrencies, including Ethereum, Binance Smart Chain tokens, and Polygon tokens. The stolen assets comprised funds from
avoid general phrases about the importance of something

2023-05-31 23:43 UTC, evgenydmitriev commented on content/attacks/posts/2010-08-10-poly-network.md
> +## Timeline
avoid bullet points without dates

2023-06-02 13:49 UTC, sln-dns commented
> 
https://www.jcp.or.jp/akahata/aik17/2018-03-02/2018030201_03_1.html

　"Of the 523 million NEMs, the virtual currency that allegedly leaked from the virtual currency exchange operator Coincheck due to unauthorized access, at least 24 million had been transferred to Zaif, a major virtual currency exchange operator in Japan, by the end of February, this paper has learned."

2023-06-02 17:10 UTC, sln-dns commented
> > 
> 
> https://www.jcp.or.jp/akahata/aik17/2018-03-02/2018030201_03_1.html
> 
> 　"Of the 523 million NEMs, the virtual currency that allegedly leaked from the virtual currency exchange operator Coincheck due to unauthorized access, at least 24 million had been transferred to Zaif, a major virtual currency exchange operator in Japan, by the end of February, this paper has learned."

It makes more sense to do one article-one pull request. 

However, I continue to do as Evgeny pointed out to me and put all the articles in one place. Maybe it is more convenient for you.

I also want to point out that the article "Poly Network" has already been accepted, nevertheless, I offered corrections for Evgeny's comments.

So at the moment, there are three articles:
1. Poly Network. Accepted but changed by Eugene's comments.
2. Coincheck Hack. Changed by Eugene's remarks.
3. Alpha Homora. Added a new one.

Thank you, it is interesting to work with you.

2023-06-03 11:26 UTC, evgenydmitriev requested changes
Please pay attention to the [file naming instructions](https://github.com/1712n/dn-institute#:~:text=YYYY%2DMM%2DDD%2Dentity%2Dthat%2Dwas%2Dhacked.md).

2023-06-05 10:26 UTC, evgenydmitriev commented
The pull request has been open for more than a week. Multiple conversation haven't been resolved. Closing.

@sln-dns if you want to submit any work in the future, try doing it in smaller chunks to make it more manageable and read up on GitHub pull request process.

2023-06-05 10:26 UTC, closed without merging