Create 2023-04-09-GDAC.md
1712n/dn-institute pull request #285
Opened 2023-10-18 17:27 UTC by svg-arch

2023-10-19 16:59 UTC, JediFaust commented
/qualitycheck

2023-10-20 16:36 UTC, JediFaust requested changes

2023-10-20 16:36 UTC, JediFaust commented on content/attacks/posts/2023-04-09-GDAC.md
> +- **April 10, 2023:** [GDAC announced the hack on their platform.](https://support.gdac.com/hc/ko/articles/17389345782041--%EA%B8%B4%EA%B8%89%EA%B3%B5%EC%A7%80-%EC%9E%85%EC%B6%9C%EA%B8%88-%EC%84%9C%E
Fix source link please

2023-10-20 16:36 UTC, JediFaust commented on content/attacks/posts/2023-04-09-GDAC.md
> +- [0x57192cca8b8e4beb77f3466c6d0550e64cc53b0f](https://etherscan.io/address/0x57192cca8b8e4beb77f3466c6d0550e64cc53b0f)
As usual, hackers utilizes a lot of addresses, please mention few of them or even single one, if there is only one marked on etherscan

2023-10-21 13:46 UTC, svg-arch commented on content/attacks/posts/2023-04-09-GDAC.md
> +- **April 10, 2023:** [GDAC announced the hack on their platform.](https://support.gdac.com/hc/ko/articles/17389345782041--%EA%B8%B4%EA%B8%89%EA%B3%B5%EC%A7%80-%EC%9E%85%EC%B6%9C%EA%B8%88-%EC%84%9C%E
There is only a Korean article and the link contains Korean letters

2023-10-21 15:50 UTC, JediFaust requested changes

2023-10-21 15:50 UTC, JediFaust commented on content/attacks/posts/2023-04-09-GDAC.md
> +- **April 10, 2023:** [GDAC announced the hack on their platform.](https://support.gdac.com/hc/ko/articles/17389345782041--%EA%B8%B4%EA%B8%89%EA%B3%B5%EC%A7%80-%EC%9E%85%EC%B6%9C%EA%B8%88-%EC%84%9C%E
I tried remove the letters after digits like this: [https://support.gdac.com/hc/ko/articles/17389345782041](https://support.gdac.com/hc/ko/articles/17389345782041) and it still refers to the same page, so it's unnecessary

2023-10-21 20:38 UTC, JediFaust approved these changes

2023-10-21 20:38 UTC, merged

2023-10-21 20:38 UTC, JediFaust commented
/payout -x 2