Shape shift
1712n/dn-institute pull request #286
Opened 2023-10-22 12:00 UTC by svg-arch

2023-10-22 19:20 UTC, JediFaust commented
/qualitycheck

2023-10-25 21:19 UTC, JediFaust requested changes

2023-10-25 21:19 UTC, JediFaust commented on content/attacks/posts/2016-03-14-ShapeShift.md
> +entity-types: Exchange
Add `Custodian`

2023-10-25 21:19 UTC, JediFaust commented on content/attacks/posts/2016-03-14-ShapeShift.md
> +From March 14 to April 9, 2016, there were 3 hacks of the Swiss ShiftShape crypto exchange.
fix `3 hacks` to `three hacks` and do so on everywhere

2023-10-25 21:19 UTC, JediFaust commented on content/attacks/posts/2016-03-14-ShapeShift.md
> +The first hack was made by an employee of the exchange. Then he left a backdoor in the system and sold access to a hacker, who committed two more hacks.
In the first sentence, I guess the word `hack` is unappropriate, and please provide more details, for example `stole the keys of exchange's hot wallet` or something. The second sentence is also can be extended with technical details.

2023-10-25 21:20 UTC, JediFaust commented
> `...more hacks. Attackers Behind the attack was an exchange employee, his name has not ...` Issue: Incorrect form of “be” Fix: `was` to `were`
> 
> `...sider fraud: An exchange employee stole cryptocurrency and left a backdoor in the system. Weak...` Issue: Missing article Fix: `cryptocurrency` to `a cryptocurrency`

Please, fix grammar issues above

2023-10-26 03:01 UTC, Williamalong23 commented
✅ Verified in all 🇱🇷 services, Recover Bitcoin, iCloud bypass, Bank loader, game hacks ,Wi-Fi recovery ,Instagram , Facebook ,Snapchat , Twitter ,Gmail, cashapp, PayPal, and other hacking job👌Contact Him 22 on Instagram for quick recovery now https://instagram.com/22cracker?igshid=YWYwM2I1ZDdmOQ==

2023-10-31 08:02 UTC, svg-arch commented
@JediFaust

2023-11-01 11:39 UTC, evgenydmitriev approved these changes
@svg-arch, when you submit articles, it would help to run your English text by GPT to make the writing style look more professional. Here's an example of a GPT prompt that might help, but feel free to experiment with it:

> Rewrite the text below in a more professional engineering voice using IT security industry vocabulary.

2023-11-01 11:40 UTC, merged

2023-11-01 11:44 UTC, evgenydmitriev commented
/payout -x 2