Add LLM-based fact-checker
1712n/dn-institute pull request #301
Opened 2023-11-02 10:17 UTC by Kseymur

Bot uses WebPilot API for fact-checking (LLM+web search). Works faster, provides links to the sources used for fact-checking. Need WebPilot key

2023-11-03 08:25 UTC, Kseymur commented
Update files with some improvements

2023-11-13 11:02 UTC, Kseymur commented
Updated with refactored files + added a config file

2023-11-13 11:19 UTC, evgenydmitriev requested changes
nice! just a few cosmetic changes needed.

2023-11-13 11:19 UTC, evgenydmitriev commented on tools/article_checker.py
> +def main():
could you add a comment for the main that describes the functionality, detailed enough for GPT to be able to generate the working code

2023-11-13 11:19 UTC, evgenydmitriev commented on tools/config.py
Config files shouldn't have executable extensions. I suggest `model.config` or something similar.

2023-11-13 13:28 UTC, Kseymur commented
done

2023-11-13 13:40 UTC, evgenydmitriev approved these changes
great, thanks! please create a test pr to the wiki after we merge this, so we can test the factcheck command. it can be any random article, we won't merge it.

2023-11-13 13:40 UTC, merged

2023-11-13 13:45 UTC, evgenydmitriev commented
/payout -x 5

2023-11-22 09:01 UTC, albina-at-inca commented
@Kseymur  could you email your BTC address to wiki.challenge.bounties@dn.institute ? Please include the QR code.