Create 2023-11-10-RaftExploit
1712n/dn-institute pull request #310
Opened 2023-11-13 19:16 UTC by aholman0725

2023-11-14 16:27 UTC, jhirschkorn requested changes

2023-11-14 16:27 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-RaftExploit
> +The exploiter minted R (which was then sold to drain AMM liquidity), and also managed to withdraw collateral at the same time.
how was teh exploiter able to mint the tokens?

2023-11-14 16:27 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-RaftExploit
> +attack-types: Liquidity token exploit
use standard attack types from list in issue

2023-11-14 16:27 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-RaftExploit
> +title: “Raft Suffers $3.3M Exploit That Drove Down Stablecoin 50%, but Hacker Likely Lost Money on Attack”
simplify title: ie "Raft Suffers 3.3M Exploit"

2023-11-16 22:14 UTC, aholman0725 commented
Requested changes complete. Thanks for clear instructions.

2023-11-20 18:04 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-RaftExploit
> +-November 10, 2023/14:49: Raft co-funder David Garai confirmed in a post on X (formerly Twitter) that the platform was targeted by an [attack](https://twitter.com/davgarai/status/1723065357445775507?
small edit: follow timing syntax convention from other articles

2023-11-20 18:28 UTC, aholman0725 commented on content/attacks/posts/2023-11-10-RaftExploit
> +-November 10, 2023/14:49: Raft co-funder David Garai confirmed in a post on X (formerly Twitter) that the platform was targeted by an [attack](https://twitter.com/davgarai/status/1723065357445775507?
Timeline format updated.

2023-11-20 20:24 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-RaftExploit
> +-**November 10, 2023, 14:49 PM:** Raft co-funder David Garai confirmed in a post on X (formerly Twitter) that the platform was targeted by an [attack](https://twitter.com/davgarai/status/172306535744
sorry, just make sure to convert times to UTC and then add "UTC"

2023-11-20 20:31 UTC, aholman0725 commented on content/attacks/posts/2023-11-10-RaftExploit
> +-**November 10, 2023, 14:49 PM:** Raft co-funder David Garai confirmed in a post on X (formerly Twitter) that the platform was targeted by an [attack](https://twitter.com/davgarai/status/172306535744
Will do. 

Is there a simple way to figure out what time zone an article is posted? A lot of the time it'll just say something like "12 hours ago".

2023-11-20 20:44 UTC, jhirschkorn approved these changes

2023-11-20 20:50 UTC, evgenydmitriev requested changes
1. fix file name
2. fix links
3. add details about the attack

2023-11-20 21:39 UTC, aholman0725 commented
> 1. fix file name
> 2. fix links
> 3. add details about the attack

Could you please expand on point number two.

2023-11-20 21:58 UTC, evgenydmitriev commented
> > 1. fix file name
> > 2. fix links
> > 3. add details about the attack
> 
> Could you please expand on point number two.

Remove all optional [URL components](https://en.wikipedia.org/wiki/URL#Syntax) (?` and `#` and everything that follows)

2023-11-27 23:32 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-RaftExploit
> +-**November 10, 2023, 14:49 PM:** Raft co-funder David Garai confirmed in a post on X (formerly Twitter) that the platform was targeted by an [attack](https://twitter.com/davgarai/status/172306535744
depends on how they timestamp it

2023-11-27 23:34 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-Raft
> +**November 10, 2023, 19:49 UTCpm:** Raft co-funder David Garai confirmed in a post on X (formerly Twitter) that the platform was targeted by an [attack.](https://twitter.com/davgarai/status/172306535
if it's 24 hr time you dont need am/pm

2023-12-07 21:14 UTC, aholman0725 commented
@evgenydmitriev requested changes made. Please let me know if I missed anything.

2023-12-13 20:03 UTC, aholman0725 commented
@evgenydmitriev I pretty much started from scratch for this article.

2023-12-28 17:06 UTC, aholman0725 commented
@JediFaust I look forward to your feedback.

2024-01-05 16:56 UTC, evgenydmitriev approved these changes

2024-01-05 16:59 UTC, evgenydmitriev commented
@aholman0725, please pay attention to the file naming convention. It is important for the wiki functioning. Also, don't forget to [explicitly re-request reviews](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review#:~:text=re%2Drequest%20review%20from%20the%20same%20reviewer) if you need us to give it another look.

2024-01-05 16:59 UTC, merged

2024-01-05 16:59 UTC, evgenydmitriev commented
/payout

2024-01-09 17:16 UTC, aholman0725 commented
@evgenydmitriev Thanks for the example for re-requests. I re-requested a few pull requests last week, but you are the listed reviewer. Not sure if you want to add Omar since he's helping. Thanks again.