Create 2023-11-10-PoloniexHeist
1712n/dn-institute pull request #311
Opened 2023-11-13 23:52 UTC by aholman0725

2023-11-14 16:34 UTC, jhirschkorn requested changes

2023-11-14 16:34 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-PoloniexHeist
> +entity-types:
see issue for stnadard entities

2023-11-14 16:34 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-PoloniexHeist
> +-Poloniex [lost](https://twitter.com/lookonchain/status/1722969227915661531) 56,000,000 worth of top altcoin ETH, 48,000,000 worth of [TRX,](https://platform.arkhamintelligence.com/explorer/address/T
delete: "top altcoin"

2023-11-14 16:34 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-PoloniexHeist
> +November 10, 2023: Poloniex announces their wallet had been closed for [maintenance](https://twitter.com/PoloSupport/status/1722934043543752968?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E17
timeline should be a sequential list
date/tiome (UTC if known): wallet closed annonced
date/time: announced extent of losses

2023-11-16 00:59 UTC, aholman0725 commented
Requested changes completed.

2023-11-20 17:41 UTC, aholman0725 commented
What's the process for updating an pull request once more information is released?

2023-11-20 18:07 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-PoloniexHeist
> +November 10, 2023: Poloniex announces their wallet had been closed for [maintenance](https://twitter.com/PoloSupport/status/1722934043543752968?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E17
![Screenshot 2023-11-20 at 10 06 33 AM](https://github.com/1712n/dn-institute/assets/81876479/a919e720-a33e-4d3d-9f9b-8bef38138097)

2023-11-20 18:22 UTC, aholman0725 commented on content/attacks/posts/2023-11-10-PoloniexHeist
> +November 10, 2023: Poloniex announces their wallet had been closed for [maintenance](https://twitter.com/PoloSupport/status/1722934043543752968?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E17
> ![Screenshot 2023-11-20 at 10 06 33 AM](https://user-images.githubusercontent.com/81876479/284353834-a919e720-a33e-4d3d-9f9b-8bef38138097.png)

Timeline format updated.

2023-11-20 20:23 UTC, jhirschkorn commented on content/attacks/posts/2023-11-10-PoloniexHeist
> +**November 10, 2023, 12:06 PM:** Poloniex announces the hack and the extent of the [losses.](https://www.fxstreet.com/cryptocurrencies/news/crypto-exchange-poloniex-hack-leads-to-60-million-in-assets
add "UTC" to the times

2023-11-20 20:32 UTC, jhirschkorn approved these changes

2023-11-20 20:33 UTC, merged

2023-11-20 20:47 UTC, evgenydmitriev commented
@aholman0725 fix the name of the file (look at other articles) and information about alleged attackers.

2023-11-22 16:17 UTC, aholman0725 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Yes ma’am. I knew we were forgetting something.  With warm regards,~Amanda Amanda O’ConnorVirtual Administrative AssistantShineBright Freelancing(516) 308-1432 From: AlbinaSent: Wednesday, November 22, 2023 4:01 AMTo: 1712n/dn-instituteCc: aholman0725; MentionSubject: Re: [1712n/dn-institute] 2023-11-10-Poloniex (PR ***@***.*** could you email your BTC address to ***@***.*** ? Please include the QT code.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 