Adds article on XYZ hack
1712n/dn-institute pull request #35
Opened 2023-05-26 05:16 UTC by AIminov

2023-05-31 15:32 UTC, eric-oconnor requested changes
This article does not provide specific details regarding an attack, it reads as a generic template for exchange attacks.  It fails to mention the assets stolen, the total amount withdrawn and broadly addresses common tactics used to extract information online. And the lessons learned read more like a broad prescription for the industry writ large, not pertaining to the attack in question.

2023-05-31 16:21 UTC, jhirschkorn commented on content/attacks/posts/2023-05-26-XYZ-exchange-hack.md
> +The XYZ Exchange hack involved a meticulously orchestrated combination of advanced hacking techniques, including social engineering, phishing, and the exploitation of vulnerabilities within the excha
what were the vulnerabilities in the exchange's infrastructure.  Follow on paragraph only talks about phishing

2023-06-02 13:17 UTC, evgenydmitriev commented
/qualitycheck

2023-06-05 10:29 UTC, evgenydmitriev commented
The pull request has been open for more than a week. Comments haven't been resolved. Closing.

2023-06-05 10:29 UTC, closed without merging