Create 2023-09-15-Remitano.md
1712n/dn-institute pull request #358
Opened 2024-02-07 10:14 UTC by svg-arch

2024-02-08 15:28 UTC, JediFaust requested changes

2024-02-08 15:28 UTC, JediFaust commented on content/attacks/posts/2023-09-15-Remitano.md
> +Remitano lost approximately $2,700,000 during the attack and $1.9 million was frozen by Tezer. The drainer swapped the stolen USDC and ANKR for 163 ETH (264000 USD) and [transferred them to HitBTC](h
There is typo: `Tezer`

2024-02-08 15:28 UTC, JediFaust commented on content/attacks/posts/2023-09-15-Remitano.md
> +Assets stolen on ETH:
ETH is a cryptocurrency, not a chain. So write as Ethereum instead.

2024-02-08 15:28 UTC, JediFaust commented on content/attacks/posts/2023-09-15-Remitano.md
> +- [537,915 USDT](https://tronscan.org/#/address/TEDNf1aqk8YJEUdNH9NRd4MqibZmdP49Fm/transfers)
The link refers to an address, not a transaction. Replace with a transaction link as in the link below.

2024-02-08 15:28 UTC, JediFaust commented on content/attacks/posts/2023-09-15-Remitano.md
> +- **2023-09-14, 03:48:59 PM UTC:** [Initial malicious transaction](https://etherscan.io/tx/0x99ad9f25df9c2597de9c8ac159f7f4d4f7139ffba0da945c4ee088f33da274e8) occured.
Fix timeline formatting as shown in other articles.

2024-02-11 09:57 UTC, JediFaust requested changes

2024-02-11 09:57 UTC, JediFaust commented on content/attacks/posts/2023-09-15-Remitano.md
> +**Compromised Private Key:** The breach was initiated through a data compromise from a third-party source, exposing sensitive information about the exchange. This security lapse enabled unauthorized
Fix formatting please, make it a point

2024-02-23 18:29 UTC, evgenydmitriev commented
/articlecheck

2024-02-23 18:32 UTC, evgenydmitriev approved these changes

2024-02-23 18:33 UTC, merged

2024-02-23 18:33 UTC, evgenydmitriev commented
/payout

2024-02-25 11:23 UTC, evgenydmitriev commented
/payout -x 2