Create 2023-07-10-Arcadia-Finance.md
1712n/dn-institute pull request #359
Opened 2024-02-07 14:02 UTC by svg-arch

2024-02-08 15:36 UTC, JediFaust requested changes
Please, fix the article according to a changes requested in your other PR's.

2024-02-11 10:02 UTC, JediFaust requested changes

2024-02-11 10:02 UTC, JediFaust commented on content/attacks/posts/2023-07-10-Arcadia-Finance.md
> +  - DeFi
Add `Lending Platform`

2024-02-11 10:02 UTC, JediFaust commented on content/attacks/posts/2023-07-10-Arcadia-Finance.md
> +- **July 10, 2023:** Arcadia Finance [published exploit Post-Mortem](https://arcadiafinance.medium.com/post-mortem-72e9d24a79b0)
Merge this events, since the timestamp is the same.

2024-02-23 18:35 UTC, evgenydmitriev commented
/articlecheck

2024-02-23 18:39 UTC, evgenydmitriev requested changes
@svg-arch please pay attention to the editor's notes from the bot

2024-03-05 11:28 UTC, JediFaust submitted a review, later dismissed

2024-03-05 11:28 UTC, JediFaust commented on content/attacks/posts/2023-07-10-Arcadia-Finance.md
> +- [Ethereum](https://phalcon.blocksec.com/explorer/tx/eth/0xefc4ac015069fdf9946997be0459db44c0491221159220be782454c32ec2d651):
Don't need to duplicate links already provided in the article. In the timeline section there are both transactions.

2024-03-05 11:28 UTC, JediFaust commented on content/attacks/posts/2023-07-10-Arcadia-Finance.md
> +- [Optimism](https://phalcon.blocksec.com/explorer/tx/optimism/0xca7c1a0fde444e1a68a8c2b8ae3fb76ec384d1f7ae9a50d26f8bfdd37c7a0afe):
Same here.

2024-03-05 11:28 UTC, JediFaust commented on content/attacks/posts/2023-07-10-Arcadia-Finance.md
> +- **Smart Contract Vulnerability:** The Arcadia Finance hack was caused by vulnerabilities in its smart contracts, particularly in functions related to vault management and liquidation. These issues
There are claims that it was Reentrancy Issue, if it is, please add 'Reentrancy Attack' to the attack types section.

2024-03-07 16:53 UTC, evgenydmitriev commented
@svg-arch, please pay attention to numbers and inconsistencies in names. For example, my spellchecker caught the A**cr**adia typo. In addition to this, I would advise using GPT4, Gemini, or Claude 3 models for double-checking your submissions before requesting a pr review. A prompt like "help me find inconsistencies in the article below" could probably address most of the problems.

2024-03-07 16:54 UTC, merged

2024-03-07 16:54 UTC, evgenydmitriev commented
/payout