Create 2022-02-02-Wormhole.md
1712n/dn-institute pull request #37
Opened 2023-05-27 03:20 UTC by Diam0ndAce

Adding an article about Wormhole hack in 2022

2023-05-31 15:37 UTC, eric-oconnor approved these changes
Good article, it aligns will with the information here: https://www.theverge.com/2022/2/3/22916111/wormhole-hack-github-error-325-million-theft-ethereum-solana

This is good as it gives us a place to reference the facts and assure accuracy of the data presented.

2023-05-31 20:00 UTC, jhirschkorn commented on content/attacks/posts/2022-02-02-Wormhole.md
> +- **Lack of the security awareness:** Wormhole team know about weakness in their bridge and the necessary code to fix this vulnerability had been written. But the code was uploaded to the Github repo
The Wormhole team knew about weaknesses in their bridge but the necessary code to fix it had been written.

This fact allowed...

2023-06-02 13:17 UTC, evgenydmitriev commented
/qualitycheck

2023-06-08 19:08 UTC, jhirschkorn commented
/qualitycheck

2023-06-08 19:09 UTC, jhirschkorn requested changes

2023-06-08 19:09 UTC, jhirschkorn commented on content/attacks/posts/2022-02-02-Wormhole.md
> +title: Wormhole lost $325 million due to hacker attack
add quotes to the title

2023-06-08 23:13 UTC, jhirschkorn commented
Conflict. Another article on this topic already exists.

2023-06-09 07:13 UTC, closed without merging