Create 2024-01-31-Abracadabra-Money.md
1712n/dn-institute pull request #373
Opened 2024-02-26 15:54 UTC by svg-arch

2024-03-05 11:40 UTC, JediFaust requested changes
Please be attentive to detail and conduct a more detailed review of the incident, avoiding unnecessary repetition and trying to capture significant events. This applies to all your submissions.

2024-03-05 11:40 UTC, JediFaust commented on content/attacks/posts/2024-01-31-Abracadabra-Money.md
> +- **January 30, 2024, 10:26:59 AM +UTC:** A [second malicious transaction](https://etherscan.io/tx/0xdb4616b89ad82062787a4e924d520639791302476484b9a6eca5126f79b6d877) occurred.
Unnecessary line

2024-03-05 11:40 UTC, JediFaust commented on content/attacks/posts/2024-01-31-Abracadabra-Money.md
> +- **January 30, 2024, 01:35 PM +UTC:** BlockSec has [detected](https://twitter.com/peckshield/status/1752279373779194011) a hack.
Please, double check the exact time of the tweet, I assume it's UTC+3 timezone. Fix such issues in your other PR's please.

2024-03-05 11:40 UTC, JediFaust commented on content/attacks/posts/2024-01-31-Abracadabra-Money.md
> +- **January 30, 2024, 11:00 AM +UTC:** MIM token was [deppeged](https://twitter.com/PeckShieldAlert/status/1752287909917659356/photo/1).
Unneseccary line.

2024-03-05 11:40 UTC, JediFaust commented on content/attacks/posts/2024-01-31-Abracadabra-Money.md
> +- **January 30, 2024, 01:35 PM +UTC:** BlockSec has [detected](https://twitter.com/peckshield/status/1752279373779194011) a hack.
BlockSec and Peckshield are different security companies. Pay attention to such details please.

2024-03-05 11:40 UTC, JediFaust commented on content/attacks/posts/2024-01-31-Abracadabra-Money.md
> +- **Smart Contract Vulnerability:** The root cause of the exploit was a flaw in how the platform's code managed numerical calculations. Specifically, the issue arose from inaccuracies in handling num
Shorten the text by removing duplications and vague phrases.

2024-03-07 17:21 UTC, evgenydmitriev commented
/articlecheck

2024-03-07 17:32 UTC, evgenydmitriev approved these changes
@svg-arch, please pay attention to the timeline order, formatting inconsistencies, and writing style best practices. GPT4-level models can help you with all of those things.

2024-03-07 17:33 UTC, merged

2024-03-07 17:33 UTC, evgenydmitriev commented
/payout