Create 2024-01-03-Radiant-Capital.md
1712n/dn-institute pull request #376
Opened 2024-02-27 13:39 UTC by svg-arch

2024-03-05 11:40 UTC, JediFaust commented
/articlecheck

2024-03-10 12:23 UTC, JediFaust requested changes

2024-03-10 12:23 UTC, JediFaust commented on content/attacks/posts/2024-01-03-Radiant-Capital.md
> +- **January 2, 2024, 06:53:38 PM UTC:** The [first malicious](https://arbiscan.io/tx/0x1ce7e9a9e3b6dd3293c9067221ac3260858ce119ecb7ca860eac28b2474c7c9b) transaction occurred.
Fix formatting of time, to match other events

2024-03-10 12:23 UTC, JediFaust commented on content/attacks/posts/2024-01-03-Radiant-Capital.md
> +- **Smart Contract Vulnerability:** There was a rounding error in the smart contract, which allowed the attacker to artificially increase the profit margin.
Two sections might be combined into one, as Smart Contract Vulnerability

2024-03-18 20:58 UTC, svg-arch commented
@JediFaust

2024-03-20 10:42 UTC, svg-arch commented
@evgenydmitriev

2024-03-20 20:13 UTC, evgenydmitriev commented
@svg-arch, given that we still have requests for changes or co-authored commits for almost all of your pull requests, I suggest you focus on improving the existing pull requests vs opening new ones. It's not a normal practice to use the pull review process for quality assurance purposes. We try to get to all of your PRs weekly, but we have limited resources and we try to spend them on meaningful reviews.

2024-04-08 14:19 UTC, evgenydmitriev commented
/articlecheck

2024-04-08 14:27 UTC, evgenydmitriev approved these changes

2024-04-08 14:28 UTC, merged

2024-04-08 14:28 UTC, evgenydmitriev commented
/payout