Create 2024-02-23-BirForex.md
1712n/dn-institute pull request #380
Opened 2024-02-29 12:43 UTC by svg-arch

2024-03-05 11:41 UTC, JediFaust commented
/articlecheck

2024-03-11 16:17 UTC, JediFaust requested changes
Overall, we have no evidence on BitForex performed exitscam. So, I suggest to wait till it's officially confirmed.

2024-03-11 16:17 UTC, JediFaust commented on content/attacks/posts/2024-02-23-BitForex.md
> +  - Exit Scam
Change to `Scam` to match other attack types

2024-03-11 16:17 UTC, JediFaust commented on content/attacks/posts/2024-02-23-BitForex.md
> +  - Wallet Hack
Remove the line

2024-03-11 16:17 UTC, JediFaust commented on content/attacks/posts/2024-02-23-BitForex.md
> +title: "BitForex's Suspicious Outflows: Hack or Exit Scam?"
Rewrite the title in the affirmative

2024-03-11 16:17 UTC, JediFaust commented on content/attacks/posts/2024-02-23-BitForex.md
> +The identity of the attacker is unknown. The following addresses are associated with this attack:
You already mentioned CEO of BitForex, you can mention him here. Preferably with sources with official accusations.

2024-03-11 16:17 UTC, JediFaust commented on content/attacks/posts/2024-02-23-BitForex.md
> +The total loss from the BitForex hack amounted to approximately [$56.5 million](https://twitter.com/zachxbt/status/1762028433574650347), distributed across the following networks:
There is no evidence that it was a hack. It's more likely to be an exitscam. [This source](https://bits.media/gonkongskiy-regulyator-obvinil-kriptobirzhu-bitforex-v-moshennichestve/) might be useful.

2024-03-11 16:17 UTC, JediFaust commented on content/attacks/posts/2024-02-23-BitForex.md
> +- **February 23, 2024, 07:12:59 PM UTC:** The withdrawal of funds from the exchange [began](https://etherscan.io/tx/0xb1ef6176112c8b019192b5e627732afee8930810801961ded081720e74544753) and the exchang
Unnecessary line. You can add a source that posted about website shutdown instead.

2024-03-11 16:17 UTC, JediFaust commented on content/attacks/posts/2024-02-23-BitForex.md
> +- **Wallet System Vulnerability:** Flaws in Bitrue’s hot wallet system have led to unauthorized access and transfers of funds.
Bitrue?

2024-03-12 18:43 UTC, JediFaust requested changes

2024-03-12 18:43 UTC, JediFaust commented on content/attacks/posts/2024-02-23-BitForex.md
> +- **March 4, 2024:** Hong Kong’s regulator for securities and futures markets has [warned](https://www.coindesk.com/policy/2024/03/04/hong-kongs-markets-regulator-issues-warning-against-crypto-exchan
Add original source from SFC

2024-03-12 18:43 UTC, JediFaust commented on content/attacks/posts/2024-02-23-BitForex.md
> +- **Wallet System Vulnerability:** Flaws in the BitForex hot wallet system have led to unauthorized access and transfers of funds.
Remove the line, since it's not a hack

2024-04-08 14:34 UTC, evgenydmitriev commented
/articlecheck

2024-04-08 14:39 UTC, evgenydmitriev approved these changes

2024-04-08 14:41 UTC, merged

2024-04-08 14:41 UTC, evgenydmitriev commented
/payout

2024-04-08 15:49 UTC, svg-arch commented
@evgenydmitriev x2 for Custodian?

2024-04-09 17:28 UTC, evgenydmitriev commented
@jhirschkorn added extra bounty for articles that involve attacks on custodians. This one is a scam, not an attack.