DAO Ethereum exploit post added
1712n/dn-institute pull request #39
Opened 2023-05-29 15:06 UTC by gavriushkinegor

Added a new post about DAO Ethereum exploit in 2016

2023-05-31 15:49 UTC, eric-oconnor approved these changes

2023-06-01 19:27 UTC, evgenydmitriev requested changes

2023-06-01 19:27 UTC, evgenydmitriev commented on content/attacks/posts/2016-06-17-DAO.md
> +title: DAO falls prey to smart contract exploit, resulting in $60 million Ether theft
this needs to be in quotes to avoid problems with special characters

2023-06-01 19:27 UTC, evgenydmitriev commented on content/attacks/posts/2016-06-17-DAO.md
> +custodians: The DAO, Ethereum
there were no custodians, you can remove this line

2023-06-01 19:27 UTC, evgenydmitriev commented on content/attacks/posts/2016-06-17-DAO.md
> +## Timeline
the timeline section needs to be significantly expanded. there are plenty of detailed descriptions of the events out there

2023-06-01 19:27 UTC, evgenydmitriev commented on content/attacks/posts/2016-06-17-DAO.md
> +## Additional Details
no need to invent sections. use the structure of already published articles

2023-06-01 19:27 UTC, evgenydmitriev commented on content/attacks/posts/2016-06-17-DAO.md
> +## Security Failure Causes
use the bullet point structure found in other published articles

2023-06-01 19:27 UTC, evgenydmitriev commented on content/attacks/posts/2016-06-17-DAO.md
> +The aftermath of the attack led to a controversial decision within the Ethereum community to enact a hard fork to recover the stolen funds, leading to a split and the creation of Ethereum Classic.
focus on fundamental security failure causes in this section

2023-06-01 19:27 UTC, evgenydmitriev commented on content/attacks/posts/2016-06-17-DAO.md
> +The perpetrator behind the DAO exploit remains undisclosed. However, they manipulated a recursive calling vulnerability in the DAO's smart contract, which permitted repeated Ether withdrawals before
focus on the facts that would narrow the pool of suspects down instead of talking about the events

2023-06-01 19:27 UTC, evgenydmitriev commented on content/attacks/posts/2016-06-17-DAO.md
> +The DAO exploit led to an estimated $60 million in Ether being transferred to the Child DAO controlled by the attacker.
talk about what ultimately happened to the funds

2023-06-02 13:16 UTC, evgenydmitriev commented
/qualitycheck

2023-06-09 13:33 UTC, marina-chibizova commented
It's been more than a week and requested changes were not implemented - closing the pr

2023-06-09 13:33 UTC, closed without merging