The Bancor Hack
1712n/dn-institute pull request #49
Opened 2023-06-01 13:04 UTC by RipperMode

2023-06-01 13:14 UTC, evgenydmitriev requested changes

2023-06-01 13:14 UTC, evgenydmitriev commented on content/attacks/posts/2018-06-18-The-Bancor-Hack.md
> +The attackers behind the Bancor hack remain unidentified. In order to execute the Bancor hack, attackers called functions of several smart contracts in the network. The attackers simply initiated a B
you are describing the events, not the attackers

2023-06-01 13:14 UTC, evgenydmitriev commented on content/attacks/posts/2018-06-18-The-Bancor-Hack.md
> +## Timeline
use bullet points and dates in every line

2023-06-01 13:14 UTC, evgenydmitriev commented on content/attacks/posts/2018-06-18-The-Bancor-Hack.md
> +## Security Failure Causes
use bullet point formatting, similar to other published articles

2023-06-01 13:14 UTC, evgenydmitriev commented on content/attacks/posts/2018-06-18-The-Bancor-Hack.md
> +Bancor has acknowledged this issue in their blog post:
focus on fundamental security failures, rather than what people said during and after the attack

2023-06-02 13:16 UTC, evgenydmitriev commented
/qualitycheck

2023-06-02 13:28 UTC, evgenydmitriev commented
/qualitycheck

2023-06-09 13:36 UTC, marina-chibizova commented
It's been more than a week and requested changes were not implemented - closing the pr

2023-06-09 13:36 UTC, closed without merging