Add Wormhole attack case
1712n/dn-institute pull request #68
Opened 2023-06-05 09:15 UTC by EvgDubrovin

2023-06-05 12:37 UTC, evgenydmitriev commented
/qualitycheck

2023-06-07 15:16 UTC, eric-oconnor commented
/qualitycheck

2023-06-07 16:53 UTC, evgenydmitriev commented
/qualitycheck

2023-06-07 17:12 UTC, evgenydmitriev commented
/qualitycheck

2023-06-07 19:32 UTC, evgenydmitriev commented
/qualitycheck

2023-06-07 19:52 UTC, evgenydmitriev requested changes
Overall, really high-quality content. Sorry for all the back-and-forth with the qualitycheck - we were fixing the fact checking bot. Could you please add links to the failed claims directly in the markdown and address the losses section comment?

2023-06-07 19:52 UTC, evgenydmitriev commented on content/attacks/posts/2023-02-02-Wormhole.md
> +## Additional Details
[Please avoid non-standard sections](https://github.com/1712n/dn-institute#:~:text=Only%20standard%20sections%20are%20allowed). This part talks about loss recovery and can easily be integrated into the Losses section.

2023-06-08 07:33 UTC, EvgDubrovin commented on content/attacks/posts/2023-02-02-Wormhole.md
> +## Additional Details
Done!

2023-06-08 07:42 UTC, EvgDubrovin commented on content/attacks/posts/2023-02-02-Wormhole.md
> +## Additional Details
Since it's a Crypto Attacks **Wiki**, I suppose it would be great to include the resources used in each article.

2023-06-08 12:13 UTC, evgenydmitriev commented
/qualitycheck

2023-06-08 14:58 UTC, evgenydmitriev commented
/qualitycheck

2023-06-08 19:41 UTC, evgenydmitriev commented
/qualitycheck

2023-06-08 19:58 UTC, evgenydmitriev approved these changes

2023-06-08 19:59 UTC, merged

2023-06-08 20:02 UTC, evgenydmitriev commented
/payout

2023-06-08 20:27 UTC, evgenydmitriev commented
/payout

2023-06-08 20:35 UTC, evgenydmitriev commented
/payout