bsc token hub exploit
1712n/dn-institute pull request #81
Opened 2023-06-06 12:56 UTC by JediFaust

BSC Token Hub exploit with over $120 Million funds lost

2023-06-08 17:04 UTC, evgenydmitriev commented
/qualitycheck

2023-06-08 17:14 UTC, JediFaust commented
So, It needs to pass every statement? And facts should be verifiable from sources?

2023-06-08 17:19 UTC, evgenydmitriev commented
> So, It needs to pass every statement? And facts should be verifiable from sources?

Sometimes, the bot gets things wrong. Someone from the wiki team will go through everything manually. That said, you can help the bot and the team by adding markdown links directly in the failed claims.

2023-06-09 12:34 UTC, JediFaust commented
/qualitycheck

2023-06-09 12:38 UTC, JediFaust commented
Sources have been added, for the failed claims, and some details omitted. When this PR will be merged, I would continue on other incidents 👏🏻

2023-06-13 17:31 UTC, jhirschkorn commented on content/attacks/posts/2022-10-06-BSC-Token-Hub.md
> +Attackers address on BSC: 0x489a8756c18c0b8b24ec2a2b9ff3d4d447f79bec
is there any known info about identity of the hackers?

2023-06-13 17:31 UTC, jhirschkorn commented on content/attacks/posts/2022-10-06-BSC-Token-Hub.md
> +2 million BNB was minted, it equals $586 million. Only $127 million worth of assets were bridged, and the rest is left frozen.
can you link a source for this one?

2023-06-13 18:18 UTC, JediFaust commented on content/attacks/posts/2022-10-06-BSC-Token-Hub.md
> +2 million BNB was minted, it equals $586 million. Only $127 million worth of assets were bridged, and the rest is left frozen.
https://www.bitget.com/academy/BNB-Chain-586-Million-dollar-Hack-The-Horror-Before-Halloween
Sure, here it is, amounts may differ a little, cause of various token prices at the moment of calculations

2023-06-13 18:24 UTC, JediFaust commented on content/attacks/posts/2022-10-06-BSC-Token-Hub.md
> +Attackers address on BSC: 0x489a8756c18c0b8b24ec2a2b9ff3d4d447f79bec
Just this address, in various chains. I may include information for each chain, and the funds in them, if it's preferred

2023-06-14 13:31 UTC, evgenydmitriev requested changes
@JediFaust, could you run your article through a spellchecker? I recommend [LanguageTool](https://languagetool.org/).

2023-06-14 14:29 UTC, JediFaust commented
@evgenydmitriev Done 👍🏻

2023-06-14 15:14 UTC, evgenydmitriev commented
/qualitycheck

2023-06-14 15:34 UTC, JediFaust commented
There is links to the sources inside the report, covering most failed claims

2023-06-14 22:26 UTC, jhirschkorn approved these changes

2023-06-20 16:04 UTC, evgenydmitriev approved these changes

2023-06-20 16:04 UTC, merged

2023-06-20 16:04 UTC, evgenydmitriev commented
/payout