Create Liquid Global
1712n/dn-institute pull request #90
Opened 2023-06-07 12:19 UTC by Rufus602

2023-06-07 20:45 UTC, evgenydmitriev commented
Before we review the content, please fix the file name and avoid using backtick quotes (`) - they [mean something different](https://golem.ph.utexas.edu/~distler/maruku/markdown_syntax.html#:~:text=To%20indicate%20a%20span%20of%20code%2C%20wrap%20it%20with%20backtick%20quotes%20(%60)) in markdown.

2023-06-07 20:45 UTC, evgenydmitriev commented
/qualitycheck

2023-06-08 04:14 UTC, Rufus602 commented
> False. The search results show that Liquid Global did provide an estimate for the loss. Multiple sources report that the hackers stole about $97 million worth of cryptocurrencies from Liquid Global. Elliptic, a blockchain analytics company, also confirmed that about $97 million in cryptocurrencies were stolen. Liquid Global stated that it was tracing the movement of the stolen cryptocurrencies and working with other exchanges to freeze and recover the assets.

Liquid Global did not provided official looses since it is regulated Japans's Financial Services Agency.

2023-06-08 04:16 UTC, Rufus602 commented
> There is no evidence in the search results to support or refute the claim. The search results only mention that the hackers stole various cryptocurrencies from the exchange, but do not provide any details on the wallets used to execute the attack.

This is link to the official blog of liquid global, where it is claimed that thief used  ERC20
https://blog.liquid.com/warm-wallet-incident

2023-06-08 04:17 UTC, Rufus602 commented
> There is no evidence in the search results to support or refute the claim that FTX lent $120 million to Liquid Global. The search results only show that Liquid Global suffered a hack and lost $97 million worth of cryptocurrencies.

Multiple articles says opposite, it is one of them: https://www.coindesk.com/business/2021/08/25/recently-hacked-exchange-liquid-global-secures-120m-loan-from-ftx/

2023-06-08 04:18 UTC, Rufus602 commented
> The claim is false. According to multiple sources, including CoinDesk and CNBC, Liquid Global was hacked on August 19, 2021, resulting in the theft of $97 million worth of cryptocurrency. As a result, the exchange suspended deposits and withdrawals. There is no evidence in the search results to suggest that Liquid Global has fully resumed deposits and withdrawals for all cryptocurrencies.

This link provides evidence:
https://blog.liquid.com/warm-wallet-incident

2023-06-08 04:20 UTC, Rufus602 commented
> The claim is false. The search results show that Liquid Global suffered a major hack in August 2021 and lost $97 million worth of cryptocurrencies. However, on August 25, 2021, it was reported that FTX would lend $120 million to Liquid Global. There is no evidence to support the claim that the loan was closed on February 2, 2022. Therefore, the claim cannot be verified and the verdict is false.

https://blog.liquid.com/liquid-ftx-dept-financing

2023-06-08 04:20 UTC, Rufus602 commented
> /qualitycheck

please re-review article since bot is wrong

2023-06-08 04:21 UTC, Rufus602 commented
> Before we review the content, please fix the file name and avoid using backtick quotes (`) - they [mean something different](https://golem.ph.utexas.edu/~distler/maruku/markdown_syntax.html#:~:text=To%20indicate%20a%20span%20of%20code%2C%20wrap%20it%20with%20backtick%20quotes%20(%60)) in markdown.

Corrected in second commit

2023-06-12 20:50 UTC, jhirschkorn requested changes

2023-06-13 17:37 UTC, jhirschkorn requested changes

2023-06-13 17:37 UTC, jhirschkorn commented on content/attacks/posts/Liquid Global
> +title: Liquid Global suffered the hack loosing about $97 million worth of digital coins
double quotes -->"

2023-06-13 17:38 UTC, jhirschkorn commented
please add links to the sources you cite here in the article

2023-06-23 15:48 UTC, jhirschkorn commented
status?

2023-06-27 20:09 UTC, JediFaust commented
The last activity was 3 weeks ago, closing

2023-06-27 20:09 UTC, closed without merging